# Generated by Django 4.2.7 on 2025-10-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cashflowsnapshot",
            new_name="dw_cashflow_company_5ba919_idx",
            old_name="analytics__company_07286d_idx",
        ),
        migrations.RenameIndex(
            model_name="salesperformancesnapshot",
            new_name="dw_sales_pe_company_8c136d_idx",
            old_name="analytics__company_5aafe1_idx",
        ),
    ]
