# Generated by Django 4.2.7 on 2025-10-24 17:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("barcode", models.CharField(blank=True, max_length=100)),
                ("acquisition_date", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "residual_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[("SL", "Straight-line"), ("DB", "Declining balance")],
                        default="SL",
                        max_length=2,
                    ),
                ),
                ("useful_life_months", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
