# Generated by Django 4.2.7 on 2025-10-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_expand_asset_and_maintenance"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_asse_company_5ef9ed_idx",
            old_name="assets_asset_company_ae4bee_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_asse_company_9be94f_idx",
            old_name="assets_asset_company_aa45ff_idx",
        ),
        migrations.RenameIndex(
            model_name="assetmaintenanceplan",
            new_name="assets_asse_company_b570bd_idx",
            old_name="assets_asset_company_648904_idx",
        ),
        migrations.RenameIndex(
            model_name="assetmaintenanceplan",
            new_name="assets_asse_company_e7c495_idx",
            old_name="assets_asset_company_135f1c_idx",
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("MAINTENANCE", "In Maintenance"),
                    ("RETIRED", "Retired"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
