# Generated by Django 4.2.7 on 2025-10-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_asset_disposal"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="downtimelog",
            new_name="assets_down_company_f6182d_idx",
            old_name="assets_down_company_ae0b2a_idx",
        ),
        migrations.RenameIndex(
            model_name="downtimelog",
            new_name="assets_down_company_409fc8_idx",
            old_name="assets_down_company_4b5b7f_idx",
        ),
    ]
