# Generated by Django 4.2.7 on 2025-10-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("procurement", "0002_alter_purchaseorder_delivery_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
    ]
