# Generated by Django 4.2.7 on 2025-10-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_purchaseorder_company_group_supplier_company_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="company_group",
        ),
    ]
