# Generated by Django 4.2.7 on 2025-10-29 17:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0005_goodsreceipt_hold_reason_and_more"),
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("budgeting", "0004_budgetline_committed_quantity_and_more"),
        ("procurement", "0004_remove_purchaseorder_company_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requisition_number",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("converted", "Converted to PO"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=12,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("stock_item", "Stock Item"),
                            ("service_item", "Service Item"),
                            ("capex_item", "Capex Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_emergency", models.BooleanField(default=False)),
                ("justification", models.TextField(blank=True)),
                ("required_by", models.DateField(blank=True, null=True)),
                (
                    "total_estimated_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "total_estimated_quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=15
                    ),
                ),
                ("workflow_state", models.CharField(blank=True, max_length=64)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "estimated_unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "estimated_total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("needed_by", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["line_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"ordering": ["-order_date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="purchaseorderline",
            options={"ordering": ["line_number"]},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["company", "code"]},
        ),
        migrations.RemoveField(
            model_name="purchaseorderline",
            name="total_price",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(default="USD", max_length=8),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="external_reference",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="workflow_state",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="budget_commitment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_lines",
                to="budgeting.budgetcommitment",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="budget_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_lines",
                to="budgeting.budgetline",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="tax_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="tolerance_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="within_tolerance",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="company",
            field=models.ForeignKey(
                help_text="Company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="inventory.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("issued", "Issued"),
                    ("partially_received", "Partially Received"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="procurement.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_lines",
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="line_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("partial", "Partially Received"),
                    ("received", "Received"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(
                help_text="Company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["company", "status"], name="procurement_company_41bc84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(
                fields=["budget_line"], name="procurement_budget__b74fc1_idx"
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisitionline",
            name="budget_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisition_lines",
                to="budgeting.budgetline",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisitionline",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisition_lines",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisitionline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requisition_lines",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisitionline",
            name="requisition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="procurement.purchaserequisition",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisitionline",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requisition_lines",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_requisitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="company",
            field=models.ForeignKey(
                help_text="Company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requisitions",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="cost_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requisitions",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raised_requisitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="procurement.purchaserequisition",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="requisition_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_lines",
                to="procurement.purchaserequisitionline",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequisitionline",
            index=models.Index(
                fields=["budget_line"], name="procurement_budget__b78b49_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaserequisitionline",
            unique_together={("requisition", "line_number")},
        ),
        migrations.AddIndex(
            model_name="purchaserequisition",
            index=models.Index(
                fields=["company", "status"], name="procurement_company_024824_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequisition",
            index=models.Index(
                fields=["company", "requisition_number"],
                name="procurement_company_6132b7_idx",
            ),
        ),
    ]
