# Generated by Django 4.2.13 on 2025-10-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_purchaserequisition_purchaserequisitionline_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorderline",
            old_name="item",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="purchaserequisitionline",
            old_name="item",
            new_name="product",
        ),
    ]
