# Generated by Django 4.2.13 on 2025-10-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0006_rename_item_purchaseorderline_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="block_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplier",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("blacklisted", "Blacklisted"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_type",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("import", "Import"),
                    ("service", "Service"),
                    ("sub_contractor", "Sub-Contractor"),
                ],
                default="local",
                max_length=20,
            ),
        ),
    ]
