# Generated by Django 4.2.13 on 2025-11-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0008_purchaserequisitiondraft"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="purchaserequisitiondraft",
            new_name="procurement_company_cda163_idx",
            old_name="proc_pr_draft_compan_bf18f3_idx",
        ),
        migrations.RenameIndex(
            model_name="purchaserequisitiondraft",
            new_name="procurement_company_d911c4_idx",
            old_name="proc_pr_draft_compan_2dfc7a_idx",
        ),
    ]
