# Generated by Django 4.2.7 on 2025-10-27 18:01

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this metadata definition (e.g., 'Entity:Customer', 'Workflow:POApproval')",
                        max_length=255,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("CORE", "Core System"),
                            ("INDUSTRY_PACK", "Industry Pack Baseline"),
                            ("GROUP_CUSTOM", "Group Customization"),
                            ("COMPANY_OVERRIDE", "Company Override"),
                        ],
                        help_text="The layer this metadata definition belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version of this metadata definition"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "definition",
                    models.JSONField(
                        help_text="The actual metadata definition in JSON format"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.companygroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "layer", "version"],
                "unique_together": {
                    ("name", "layer", "company_group", "company", "version")
                },
            },
        ),
    ]
