# Generated by Django 4.2.7 on 2025-10-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metadatadefinition",
            options={"ordering": ["key", "-version"]},
        ),
        migrations.AlterUniqueTogether(
            name="metadatadefinition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_metadata_definitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="key",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Stable identifier (e.g., 'entity.customer', 'form.purchase_order').",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ENTITY", "Entity Definition"),
                    ("FORM", "Form Definition"),
                    ("LIST", "List View Definition"),
                    ("WORKFLOW", "Workflow Definition"),
                    ("DASHBOARD", "Dashboard Definition"),
                    ("WIDGET", "Dashboard Widget Definition"),
                ],
                default="FORM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("GLOBAL", "Global"),
                    ("GROUP", "Company Group"),
                    ("COMPANY", "Company"),
                ],
                default="COMPANY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Lightweight summary for UI listings.",
            ),
        ),
        migrations.AddField(
            model_name="metadatadefinition",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_metadata_definitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="metadatadefinition",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_definitions",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="metadatadefinition",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_definitions",
                to="companies.companygroup",
            ),
        ),
        migrations.AlterField(
            model_name="metadatadefinition",
            name="definition",
            field=models.JSONField(
                default=dict, help_text="Versioned metadata payload."
            ),
        ),
        migrations.AlterField(
            model_name="metadatadefinition",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="metadatadefinition",
            name="layer",
            field=models.CharField(
                choices=[
                    ("CORE", "Core System"),
                    ("INDUSTRY_PACK", "Industry Pack Baseline"),
                    ("GROUP_CUSTOM", "Group Customization"),
                    ("COMPANY_OVERRIDE", "Company Override"),
                ],
                default="COMPANY_OVERRIDE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metadatadefinition",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="metadatadefinition",
            index=models.Index(
                fields=["kind", "key", "status"], name="metadata_me_kind_c0ef95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadatadefinition",
            index=models.Index(
                fields=["scope_type", "company_group", "company"],
                name="metadata_me_scope_t_85587e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadatadefinition",
            constraint=models.UniqueConstraint(
                fields=(
                    "key",
                    "kind",
                    "layer",
                    "scope_type",
                    "company_group",
                    "company",
                    "version",
                ),
                name="uniq_metadata_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadatadefinition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("company__isnull", True),
                        ("company_group__isnull", True),
                        ("scope_type", "GLOBAL"),
                    ),
                    models.Q(("company_group__isnull", False), ("scope_type", "GROUP")),
                    models.Q(("company__isnull", False), ("scope_type", "COMPANY")),
                    _connector="OR",
                ),
                name="metadata_scope_consistency",
            ),
        ),
        migrations.RemoveField(
            model_name="metadatadefinition",
            name="name",
        ),
    ]
