# Generated by Django 4.2.7 on 2025-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0002_alter_metadatadefinition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatadefinition",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ENTITY", "Entity Definition"),
                    ("FORM", "Form Definition"),
                    ("LIST", "List View Definition"),
                    ("WORKFLOW", "Workflow Definition"),
                    ("DASHBOARD", "Dashboard Definition"),
                    ("WIDGET", "Dashboard Widget Definition"),
                    ("REPORT", "Report Definition"),
                ],
                default="FORM",
                max_length=20,
            ),
        ),
    ]
