# Generated by Django 4.2.13 on 2025-11-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0004_documentsequence"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentsequence",
            new_name="metadata_do_company_414fab_idx",
            old_name="metadata_docseq_idx",
        ),
    ]
