# Generated by Django 4.2.7 on 2025-10-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("inventory", "0002_deliveryorder_goodsreceipt_stocklevel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryorder",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warehouse",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
    ]
