# Generated by Django 4.2.7 on 2025-10-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_deliveryorder_company_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryorder",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="goodsreceipt",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="product",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="stocklevel",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="unitofmeasure",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="company_group",
        ),
    ]
