# Generated by Django 4.2.7 on 2025-10-29 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0004_remove_deliveryorder_company_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="hold_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="quality_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="quality_checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("on_hold", "On Hold"),
                    ("passed", "Passed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
