# Generated by Django 4.2.13 on 2025-10-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_goodsreceipt_hold_reason_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryorderline",
            old_name="item",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="goodsreceiptline",
            old_name="item",
            new_name="product",
        ),
    ]
