# Generated by Django 4.2.13 on 2025-11-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_unitofmeasure_short_name"),
        ("inventory", "0006_rename_item_deliveryorderline_product_and_more"),
    ]

    operations = []
