# Generated by Django 4.2.13 on 2025-11-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("inventory", "0008_internalrequisition"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="internalrequisition",
            new_name="inventory_i_company_711f7a_idx",
            old_name="inventory_intern_compan_b7c2c8_idx",
        ),
        migrations.RenameIndex(
            model_name="internalrequisition",
            new_name="inventory_i_company_71147a_idx",
            old_name="inventory_intern_compan_3c7a6d_idx",
        ),
        migrations.AlterField(
            model_name="internalrequisition",
            name="company",
            field=models.ForeignKey(
                help_text="Company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.company",
            ),
        ),
    ]
