# Generated by Django 4.2.13 on 2025-11-05 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0005_branch_department_departmentmembership_and_more"),
        (
            "inventory",
            "0009_rename_inventory_intern_compan_b7c2c8_idx_inventory_i_company_711f7a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockledger",
            name="layer_consumed_detail",
            field=models.JSONField(
                blank=True,
                help_text="Details of cost layers consumed: [{layer_id, qty_consumed, cost_per_unit}]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="valuation_method_used",
            field=models.CharField(
                blank=True,
                help_text="Valuation method used for this transaction (FIFO/LIFO/AVG/STANDARD)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ValuationChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "old_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "First In, First Out"),
                            ("LIFO", "Last In, First Out"),
                            ("WEIGHTED_AVG", "Weighted Average"),
                            ("STANDARD", "Standard Cost"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "First In, First Out"),
                            ("LIFO", "Last In, First Out"),
                            ("WEIGHTED_AVG", "Weighted Average"),
                            ("STANDARD", "Standard Cost"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date when change becomes effective"),
                ),
                (
                    "old_inventory_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Inventory value before change",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "new_inventory_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Inventory value after change",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "revaluation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Adjustment amount (positive = increase, negative = decrease)",
                        max_digits=20,
                    ),
                ),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EFFECTIVE", "Effective (Applied)"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Business reason for the change"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason if rejected"),
                ),
                (
                    "revaluation_je_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Journal Entry ID for revaluation posting",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuation_changes_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_changes",
                        to="inventory.product",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuation_changes_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_changes",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valuation Change Log",
                "verbose_name_plural": "Valuation Change Logs",
                "ordering": ["-requested_date"],
                "indexes": [
                    models.Index(
                        fields=["company", "product", "warehouse"],
                        name="inventory_v_company_79c5e8_idx",
                    ),
                    models.Index(
                        fields=["status", "-requested_date"],
                        name="inventory_v_status_cade5a_idx",
                    ),
                    models.Index(
                        fields=["effective_date"], name="inventory_v_effecti_0feafd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemValuationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "First In, First Out"),
                            ("LIFO", "Last In, First Out"),
                            ("WEIGHTED_AVG", "Weighted Average"),
                            ("STANDARD", "Standard Cost"),
                        ],
                        default="FIFO",
                        max_length=20,
                    ),
                ),
                (
                    "avg_period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("PERPETUAL", "Perpetual (Moving Average)"),
                        ],
                        default="PERPETUAL",
                        help_text="Applicable only for Weighted Average method",
                        max_length=20,
                    ),
                ),
                (
                    "allow_negative_inventory",
                    models.BooleanField(
                        default=False,
                        help_text="Allow stock to go negative (backorders)",
                    ),
                ),
                (
                    "prevent_cost_below_zero",
                    models.BooleanField(
                        default=True,
                        help_text="Prevent cost per unit from going below zero",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date from which this valuation method is effective"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_methods",
                        to="inventory.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_methods",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Valuation Method",
                "verbose_name_plural": "Item Valuation Methods",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["company", "product", "warehouse", "-effective_date"],
                        name="inventory_i_company_768953_idx",
                    ),
                    models.Index(
                        fields=["company", "product", "is_active"],
                        name="inventory_i_company_d241fc_idx",
                    ),
                ],
                "unique_together": {
                    ("company", "product", "warehouse", "effective_date")
                },
            },
        ),
        migrations.CreateModel(
            name="CostLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt_date",
                    models.DateTimeField(
                        help_text="When this layer was created (receipt timestamp)"
                    ),
                ),
                (
                    "qty_received",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Original quantity received in this layer",
                        max_digits=15,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cost per unit at receipt (includes landed cost if already known)",
                        max_digits=20,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of layer (qty_received × cost_per_unit)",
                        max_digits=20,
                    ),
                ),
                (
                    "qty_remaining",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity still available in this layer (updated on consumption)",
                        max_digits=15,
                    ),
                ),
                (
                    "cost_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost remaining in this layer (qty_remaining × cost_per_unit)",
                        max_digits=20,
                    ),
                ),
                (
                    "fifo_sequence",
                    models.IntegerField(
                        help_text="Sequence number for FIFO ordering (auto-incremented per product+warehouse)"
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, help_text="Batch number if tracked", max_length=50
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, help_text="Serial number if tracked", max_length=50
                    ),
                ),
                (
                    "is_standard_cost",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a standard cost layer (not actual receipt)",
                    ),
                ),
                (
                    "landed_cost_adjustment",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Additional cost per unit from landed cost (freight, duty, etc.)",
                        max_digits=20,
                    ),
                ),
                (
                    "adjustment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When landed cost adjustment was applied",
                        null=True,
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(
                        blank=True, help_text="Reason for cost adjustment"
                    ),
                ),
                (
                    "source_document_type",
                    models.CharField(
                        help_text="Type of source document (GoodsReceipt, StockMovement, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "source_document_id",
                    models.IntegerField(help_text="ID of source document"),
                ),
                (
                    "immutable_after_post",
                    models.BooleanField(
                        default=True,
                        help_text="Once consumed, cost_per_unit cannot change (only qty_remaining updates)",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="True when qty_remaining = 0 (fully consumed)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layers",
                        to="inventory.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layers",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Layer",
                "verbose_name_plural": "Cost Layers",
                "ordering": ["fifo_sequence", "receipt_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["company", "product", "warehouse", "is_closed"],
                        name="inventory_c_company_1b2df0_idx",
                    ),
                    models.Index(
                        fields=["company", "product", "warehouse", "fifo_sequence"],
                        name="inventory_c_company_b24896_idx",
                    ),
                    models.Index(
                        fields=["receipt_date"], name="inventory_c_receipt_da4e11_idx"
                    ),
                    models.Index(
                        fields=["source_document_type", "source_document_id"],
                        name="inventory_c_source__69a819_idx",
                    ),
                ],
            },
        ),
    ]
