# Generated by Django 4.2.13 on 2025-11-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_product_expiry_controls"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="costlayer",
            name="inv_costlayer_expiry_idx",
        ),
        migrations.RenameIndex(
            model_name="costlayer",
            new_name="inventory_c_company_abb635_idx",
            old_name="inv_costlayer_state_idx",
        ),
    ]
