# Generated by Django 4.2.13 on 2025-11-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_remove_costlayer_inv_costlayer_expiry_idx_and_more"),
        ("inventory", "9999_add_abc_ved_classification"),
    ]

    operations = []
