# Generated by Django 4.2.13 on 2025-11-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("inventory", "10005_uom_add_group_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitofmeasure",
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
            },
        ),
        migrations.RemoveConstraint(
            model_name="unitofmeasure",
            name="uom_unique_per_group_code",
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Company group (for group-wide uniqueness)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
        ),
    ]
