# Generated by Django 4.2.13 on 2025-11-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10007_warehousebin_movementevent_itemwarehouseconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovementline",
            name="entered_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Original quantity in entered UoM",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmovementline",
            name="entered_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entered_stock_movement_lines",
                to="inventory.unitofmeasure",
            ),
        ),
    ]
