# Generated by Django 4.2.13 on 2025-11-10 12:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def seed_item_operational_data(apps, schema_editor):
    Item = apps.get_model("inventory", "Item")
    ItemOperationalExtension = apps.get_model("inventory", "ItemOperationalExtension")
    ItemWarehouseConfig = apps.get_model("inventory", "ItemWarehouseConfig")

    for item in Item.objects.select_related("company", "uom").all():
        stock_uom_id = item.uom_id
        ItemOperationalExtension.objects.get_or_create(
            item=item,
            defaults={
                "company_id": item.company_id,
                "stock_uom_id": stock_uom_id,
                "purchase_uom_id": stock_uom_id,
                "sales_uom_id": stock_uom_id,
                "requires_batch_tracking": item.track_batch,
                "requires_serial_tracking": item.track_serial,
                "requires_expiry_tracking": bool(item.expiry_warning_days),
                "expiry_warning_days": item.expiry_warning_days or 0,
                "allow_negative_inventory": False,
            },
        )

        ItemWarehouseConfig.objects.get_or_create(
            item=item,
            warehouse=None,
            defaults={
                "company_id": item.company_id,
                "pack_size_uom_id": stock_uom_id,
                "pack_size_qty": Decimal("1.000"),
                "min_stock_level": item.reorder_level or Decimal("0.000"),
                "max_stock_level": (item.reorder_level or Decimal("0.000")) * 2,
                "reorder_point": item.reorder_level or Decimal("0.000"),
                "economic_order_qty": item.reorder_quantity or Decimal("0.000"),
                "lead_time_days": item.lead_time_days or 0,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "10006_alter_unitofmeasure_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_bins",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bins",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse Bin",
                "verbose_name_plural": "Warehouse Bins",
            },
        ),
        migrations.CreateModel(
            name="MovementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("ISSUE", "Issue"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("SCRAP", "Scrap / Loss"),
                            ("CYCLE_COUNT", "Cycle Count Adjustment"),
                            ("REVERSAL", "Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "qty_change",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Positive for receipts, negative for issues",
                        max_digits=18,
                    ),
                ),
                (
                    "source_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("event_date", models.DateField()),
                ("event_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_document_type",
                    models.CharField(blank=True, max_length=50),
                ),
                ("reference_document_id", models.IntegerField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                (
                    "cost_per_unit_at_event",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=20
                    ),
                ),
                ("valuation_method_used", models.CharField(blank=True, max_length=20)),
                ("event_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "immutable_after_posting",
                    models.BooleanField(
                        default=True,
                        help_text="If true, record cannot be edited once persisted",
                    ),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movement_events",
                        to="inventory.warehousebin",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_events",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_events",
                        to="inventory.item",
                    ),
                ),
                (
                    "source_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_events_source",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "stock_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_events",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movement_events",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_movement_event",
                "ordering": ["-event_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ItemWarehouseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pack_size_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=15
                    ),
                ),
                (
                    "min_stock_level",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=15
                    ),
                ),
                (
                    "max_stock_level",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=15
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=15
                    ),
                ),
                (
                    "economic_order_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="EOQ (economic order quantity)",
                        max_digits=15,
                    ),
                ),
                ("lead_time_days", models.IntegerField(default=0)),
                ("lead_time_std_dev", models.IntegerField(default=0)),
                (
                    "demand_std_dev",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=15
                    ),
                ),
                (
                    "service_level_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("95.00"), max_digits=5
                    ),
                ),
                ("allow_negative_inventory", models.BooleanField(default=False)),
                ("allow_backorder_generation", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_warehouse_configs",
                        to="companies.company",
                    ),
                ),
                (
                    "default_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_items",
                        to="inventory.warehousebin",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_configs",
                        to="inventory.item",
                    ),
                ),
                (
                    "pack_size_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pack_size_items",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_configs",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Warehouse Configuration",
                "db_table": "inventory_item_warehouse_config",
            },
        ),
        migrations.CreateModel(
            name="ItemUOMConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Quantity of to_uom in one from_uom",
                        max_digits=20,
                    ),
                ),
                (
                    "rounding_rule",
                    models.CharField(
                        choices=[
                            ("ROUND_UP", "Round Up"),
                            ("ROUND_DOWN", "Round Down"),
                            ("ROUND_NEAREST", "Round Nearest"),
                            ("TRUNCATE", "Truncate"),
                            ("NO_ROUNDING", "No Rounding"),
                        ],
                        default="NO_ROUNDING",
                        max_length=20,
                    ),
                ),
                ("is_purchase_conversion", models.BooleanField(default=False)),
                ("is_sales_conversion", models.BooleanField(default=False)),
                ("is_stock_conversion", models.BooleanField(default=False)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("precedence", models.IntegerField(default=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_uom_conversions",
                        to="companies.company",
                    ),
                ),
                (
                    "from_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversion_from_uom",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uom_conversions",
                        to="inventory.item",
                    ),
                ),
                (
                    "to_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversion_to_uom",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_item_uom_conversion",
            },
        ),
        migrations.CreateModel(
            name="ItemOperationalExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=64)),
                ("qr_code", models.CharField(blank=True, max_length=64)),
                ("hazmat_class", models.CharField(blank=True, max_length=30)),
                (
                    "hazmat_signal_word",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DANGER", "Danger"),
                            ("WARNING", "Warning"),
                            ("CAUTION", "Caution"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "storage_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRY", "Dry"),
                            ("FROZEN", "Frozen"),
                            ("CLIMATE", "Climate Controlled"),
                            ("HAZMAT", "Hazardous Material"),
                            ("OUTDOOR", "Outdoor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("handling_instructions", models.TextField(blank=True)),
                ("requires_batch_tracking", models.BooleanField(default=False)),
                ("requires_serial_tracking", models.BooleanField(default=False)),
                ("requires_expiry_tracking", models.BooleanField(default=False)),
                ("expiry_warning_days", models.PositiveIntegerField(default=0)),
                ("allow_negative_inventory", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_operational_profiles",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_profile",
                        to="inventory.item",
                    ),
                ),
                (
                    "purchase_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "sales_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_items",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "stock_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Operational Extension",
                "db_table": "inventory_item_operational_extension",
            },
        ),
        migrations.AddIndex(
            model_name="warehousebin",
            index=models.Index(
                fields=["company", "warehouse"], name="inventory_w_company_7762fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousebin",
            index=models.Index(
                fields=["is_active"], name="inventory_w_is_acti_cb5ca4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="warehousebin",
            unique_together={("warehouse", "code")},
        ),
        migrations.AddIndex(
            model_name="movementevent",
            index=models.Index(
                fields=["company", "item", "warehouse"],
                name="inventory_m_company_5e6368_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="movementevent",
            index=models.Index(
                fields=["event_date"], name="inventory_m_event_d_dcf5e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movementevent",
            index=models.Index(
                fields=["reference_document_type", "reference_document_id"],
                name="inventory_m_referen_243362_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemwarehouseconfig",
            index=models.Index(
                fields=["company", "warehouse", "is_active"],
                name="inventory_i_company_61fc9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemwarehouseconfig",
            index=models.Index(
                fields=["company", "item", "reorder_point"],
                name="inventory_i_company_bc0433_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemwarehouseconfig",
            unique_together={("item", "warehouse", "is_active")},
        ),
        migrations.AddIndex(
            model_name="itemuomconversion",
            index=models.Index(
                fields=["company", "item", "effective_date"],
                name="inventory_i_company_a0f9db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemuomconversion",
            index=models.Index(
                fields=["company", "item", "from_uom", "to_uom"],
                name="inventory_i_company_8116e9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemuomconversion",
            unique_together={
                ("item", "from_uom", "to_uom", "effective_date", "precedence")
            },
        ),
        migrations.AddIndex(
            model_name="itemoperationalextension",
            index=models.Index(
                fields=["company", "hazmat_class"],
                name="inventory_i_company_3343bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemoperationalextension",
            index=models.Index(
                fields=["company", "storage_class"],
                name="inventory_i_company_cd2207_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemoperationalextension",
            index=models.Index(
                fields=["requires_batch_tracking", "requires_serial_tracking"],
                name="inventory_i_require_a2f7d5_idx",
            ),
        ),
        migrations.RunPython(
            seed_item_operational_data, migrations.RunPython.noop
        ),
    ]
