# Generated by Django 4.2.13 on 2025-11-05 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_currency_account_currency_balances_and_more"),
        ("companies", "0006_company_default_data_loaded_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "10000_merge_20251105_1529"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("RAW_MATERIAL", "Raw Material"),
                            ("CONSUMABLE", "Consumable"),
                            ("COMPONENT", "Component"),
                            ("FIXED_ASSET", "Fixed Asset"),
                            ("SERVICE", "Service"),
                            ("SEMI_FINISHED", "Semi-Finished Good"),
                            ("PACKING_MATERIAL", "Packing Material"),
                            ("SPARE_PART", "Spare Part"),
                            ("TOOL", "Tool"),
                        ],
                        default="RAW_MATERIAL",
                        help_text="Type of item",
                        max_length=20,
                    ),
                ),
                (
                    "is_tradable",
                    models.BooleanField(
                        default=False,
                        help_text="If True, can be linked to a saleable Product",
                    ),
                ),
                ("track_inventory", models.BooleanField(default=True)),
                ("track_serial", models.BooleanField(default=False)),
                ("track_batch", models.BooleanField(default=False)),
                ("prevent_expired_issuance", models.BooleanField(default=True)),
                ("expiry_warning_days", models.PositiveIntegerField(default=0)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "First In, First Out"),
                            ("LIFO", "Last In, First Out"),
                            ("WEIGHTED_AVG", "Weighted Average"),
                            ("STANDARD_COST", "Standard Cost"),
                        ],
                        default="FIFO",
                        max_length=20,
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("lead_time_days", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legacy_product_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Link to original Product record",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "db_table": "inventory_item",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "hierarchy_path",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=500
                    ),
                ),
                ("level", models.IntegerField(default=0, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default_template",
                    models.BooleanField(
                        default=False, help_text="System default category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Item Categories",
                "db_table": "inventory_item_category",
                "ordering": ["hierarchy_path", "code"],
            },
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "Legacy Product Categories"},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="inv_prod_abc_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="inv_prod_ved_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="abc_classification",
        ),
        migrations.RemoveField(
            model_name="product",
            name="abc_classification_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="ved_classification",
        ),
        migrations.RemoveField(
            model_name="product",
            name="ved_classification_date",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_products",
                to="inventory.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                help_text="Company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_inventory_products",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_products",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="company",
            field=models.ForeignKey(
                help_text="Company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_product_categories",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_sub_categories",
                to="inventory.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="companies.company"
            ),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_categories",
                to="inventory.itemcategory",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Item category",
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.itemcategory",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="company",
            field=models.ForeignKey(
                help_text="Company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expense_items",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_items",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["company", "is_active"], name="inventory_i_company_c48ca0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["hierarchy_path"], name="inventory_i_hierarc_9cb594_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemcategory",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["company", "category"], name="inventory_i_company_f3f9cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["company", "item_type"], name="inventory_i_company_73234c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["company", "is_active"], name="inventory_i_company_9effa4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("company", "code")},
        ),
    ]
