# Generated by Django 4.2.13 on 2025-11-10 13:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0010_alter_product_fk_to_item"),
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("inventory", "10008_stockmovementline_entered_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_item_code", models.CharField(blank=True, max_length=100)),
                (
                    "supplier_pack_size",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=15
                    ),
                ),
                (
                    "moq_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Minimum order quantity",
                        max_digits=15,
                    ),
                ),
                (
                    "multiple_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Order multiples",
                        max_digits=15,
                    ),
                ),
                ("lead_time_days", models.IntegerField(default=0)),
                (
                    "lead_time_variability",
                    models.IntegerField(
                        default=0, help_text="Std dev of lead time in days"
                    ),
                ),
                (
                    "preferred_rank",
                    models.IntegerField(default=1, help_text="1 = preferred supplier"),
                ),
                (
                    "last_purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("last_purchase_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_suppliers",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_links",
                        to="inventory.item",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_links",
                        to="procurement.supplier",
                    ),
                ),
                (
                    "supplier_pack_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_pack_items",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_item_supplier",
                "ordering": ["preferred_rank", "supplier_id"],
                "indexes": [
                    models.Index(
                        fields=["company", "item"],
                        name="inventory_i_company_a6f1f2_idx",
                    ),
                    models.Index(
                        fields=["company", "supplier"],
                        name="inventory_i_company_265815_idx",
                    ),
                    models.Index(
                        fields=["item", "preferred_rank"],
                        name="inventory_i_item_id_1403db_idx",
                    ),
                ],
                "unique_together": {("item", "supplier")},
            },
        ),
    ]
