# Generated by Django 4.2.13 on 2025-11-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10018_event_linkages"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="item",
            name="inventory_item_company_budget_item_unique",
        ),
    ]
