# Generated by Django 4.2.13 on 2025-11-10 13:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10011_alter_stockmovement_status_intransitshipmentline"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemwarehouseconfig",
            name="auto_replenish",
            field=models.BooleanField(
                default=False, help_text="Enable automated replenishment logic"
            ),
        ),
        migrations.AddField(
            model_name="itemwarehouseconfig",
            name="avg_daily_demand",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Average daily demand",
                max_digits=15,
            ),
        ),
    ]
