# Generated by Django 4.2.13 on 2025-11-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("inventory", "10009_itemsupplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemFEFOConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enforce_fefo", models.BooleanField(default=False)),
                ("warn_days_before_expiry", models.PositiveIntegerField(default=0)),
                ("block_issue_if_expired", models.BooleanField(default=True)),
                (
                    "disposal_method",
                    models.CharField(
                        choices=[
                            ("SCRAP", "Scrap"),
                            ("DONATE", "Donate"),
                            ("RETURN_TO_SUPPLIER", "Return to Supplier"),
                            ("REWORK", "Rework"),
                        ],
                        default="SCRAP",
                        max_length=30,
                    ),
                ),
                (
                    "expiry_calculation_rule",
                    models.CharField(
                        choices=[
                            ("FIXED_DATE", "Fixed Date"),
                            ("DAYS_FROM_MFG", "Days from Manufacture"),
                            ("DAYS_FROM_RECEIPT", "Days from Receipt"),
                            ("CUSTOM", "Custom Formula"),
                        ],
                        default="FIXED_DATE",
                        max_length=30,
                    ),
                ),
                ("shelf_life_days", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_fefo_configs",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fefo_configs",
                        to="inventory.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fefo_configs",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_item_fefo_config",
                "indexes": [
                    models.Index(
                        fields=["company", "item"],
                        name="inventory_i_company_7e4b7d_idx",
                    ),
                    models.Index(
                        fields=["company", "warehouse"],
                        name="inventory_i_company_9b5086_idx",
                    ),
                ],
                "unique_together": {("item", "warehouse")},
            },
        ),
    ]
