# Generated by Django 4.2.13 on 2025-11-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0028_line_workflow_backfill"),
        ("projects", "0001_initial"),
        ("inventory", "10012_itemwarehouseconfig_auto_replenish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intransitshipmentline",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="intransitshipmentline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_ledger_entries",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_ledger_entries",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="stockmovementline",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movement_lines",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="stockmovementline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movement_lines",
                to="projects.project",
            ),
        ),
    ]
