# Generated by Django 4.2.13 on 2025-11-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("inventory", "10010_itemfefoconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_TRANSIT", "In Transit"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InTransitShipmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=20)),
                ("batch_no", models.CharField(blank=True, max_length=50)),
                ("serial_no", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="in_transit_lines",
                        to="companies.company",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="in_transit_out",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_transit_lines",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "movement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_transit_entries",
                        to="inventory.stockmovementline",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="in_transit_in",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company", "item"],
                        name="inventory_i_company_cabb19_idx",
                    ),
                    models.Index(
                        fields=["company", "from_warehouse"],
                        name="inventory_i_company_395136_idx",
                    ),
                    models.Index(
                        fields=["company", "to_warehouse"],
                        name="inventory_i_company_a57666_idx",
                    ),
                ],
            },
        ),
    ]
