# Generated by Django 4.2.13 on 2025-11-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10023_phase3_qc_compliance"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptline",
            name="certificate_of_analysis",
            field=models.FileField(
                blank=True,
                help_text="Certificate of Analysis document",
                null=True,
                upload_to="qc/coa/",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="manufacturer_batch_no",
            field=models.CharField(
                blank=True, help_text="Manufacturer's batch/lot number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="serial_numbers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of serial numbers for serialized items",
            ),
        ),
    ]
