# Generated by Django 4.2.13 on 2025-11-11 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0028_line_workflow_backfill"),
        ("inventory", "10021_returntovendor_landedcostvoucher_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returntovendorline",
            name="budget_item_id",
        ),
        migrations.RemoveField(
            model_name="returntovendorline",
            name="budget_line_id",
        ),
        migrations.RemoveField(
            model_name="returntovendorline",
            name="movement_event_id",
        ),
        migrations.AddField(
            model_name="returntovendorline",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rtv_reversals",
                to="budgeting.budgetline",
            ),
        ),
        migrations.AddField(
            model_name="returntovendorline",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of items being returned"
            ),
        ),
        migrations.AddField(
            model_name="returntovendorline",
            name="movement_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Negative movement event created for this return",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rtv_lines",
                to="inventory.movementevent",
            ),
        ),
        migrations.AddField(
            model_name="returntovendorline",
            name="quality_notes",
            field=models.TextField(
                blank=True, help_text="Quality inspection notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="returntovendorline",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Specific reason for this line",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="returntovendorline",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.unitofmeasure",
            ),
        ),
    ]
