# Generated by Django 4.2.13 on 2025-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10028_auto_generate_bin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="itemcategory",
            name="code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
