# Generated by Django 4.2.13 on 2025-11-11 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "10020_landedcostcomponent_standardcostvariance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnToVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rtv_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("rtv_date", models.DateField()),
                ("supplier_id", models.IntegerField(help_text="Supplier to return to")),
                (
                    "return_reason",
                    models.CharField(
                        choices=[
                            ("DEFECTIVE", "Defective/Damaged Goods"),
                            ("WRONG_ITEM", "Wrong Item Received"),
                            ("EXCESS_QUANTITY", "Excess Quantity"),
                            ("QUALITY_ISSUE", "Quality Issue"),
                            ("EXPIRED", "Expired/Near Expiry"),
                            ("NOT_ORDERED", "Not Ordered"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "return_reason_detail",
                    models.TextField(help_text="Detailed explanation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Approval"),
                            ("APPROVED", "Approved"),
                            ("IN_TRANSIT", "In Transit to Vendor"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_return_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total value being returned",
                        max_digits=20,
                    ),
                ),
                ("refund_expected", models.BooleanField(default=True)),
                ("refund_received", models.BooleanField(default=False)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("refund_date", models.DateField(blank=True, null=True)),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("shipped_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "je_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Journal Entry ID for return posting",
                        null=True,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False)),
                ("gl_posted_date", models.DateTimeField(blank=True, null=True)),
                ("debit_note_number", models.CharField(blank=True, max_length=100)),
                ("debit_note_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vendor_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_returns",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_vendor_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return To Vendor",
                "verbose_name_plural": "Returns To Vendor",
                "ordering": ["-rtv_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandedCostVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voucher_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("voucher_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "supplier_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Supplier providing the service",
                        null=True,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("ALLOCATED", "Allocated to Cost Layers"),
                            ("POSTED", "Posted to GL"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total landed cost to be allocated",
                        max_digits=20,
                    ),
                ),
                (
                    "allocated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount already allocated to cost layers",
                        max_digits=20,
                    ),
                ),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "je_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Journal Entry ID when posted to GL",
                        null=True,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False)),
                ("gl_posted_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_landed_cost_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_landed_cost_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_landed_cost_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Landed Cost Voucher",
                "verbose_name_plural": "Landed Cost Vouchers",
                "ordering": ["-voucher_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandedCostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount allocated to this line",
                        max_digits=20,
                    ),
                ),
                (
                    "allocation_basis",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Basis value used for allocation (qty, value, weight, etc.)",
                        max_digits=20,
                    ),
                ),
                (
                    "allocation_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Percentage of total cost allocated",
                        max_digits=7,
                    ),
                ),
                (
                    "original_cost_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cost per unit before allocation",
                        max_digits=15,
                    ),
                ),
                (
                    "cost_per_unit_adjustment",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Per-unit cost increase from this allocation",
                        max_digits=15,
                    ),
                ),
                (
                    "new_cost_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cost per unit after allocation",
                        max_digits=15,
                    ),
                ),
                (
                    "to_inventory",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount allocated to remaining inventory",
                        max_digits=20,
                    ),
                ),
                (
                    "to_cogs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount allocated to consumed goods (COGS)",
                        max_digits=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Allocation"),
                            ("ALLOCATED", "Allocated to Cost Layers"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("allocated_date", models.DateTimeField(blank=True, null=True)),
                ("reversed_date", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landed_cost_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "cost_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landed_cost_allocations",
                        to="inventory.costlayer",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landed_cost_allocations",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "goods_receipt_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landed_cost_allocations",
                        to="inventory.goodsreceiptline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_landed_cost_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="inventory.landedcostvoucher",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landed Cost Allocation",
                "verbose_name_plural": "Landed Cost Allocations",
                "ordering": ["voucher", "goods_receipt", "goods_receipt_line"],
            },
        ),
        migrations.CreateModel(
            name="ReturnToVendorLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_to_return",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity being returned (in stock UoM)",
                        max_digits=15,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Original unit cost from GRN",
                        max_digits=15,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value of this line",
                        max_digits=20,
                    ),
                ),
                ("batch_lot_id", models.IntegerField(blank=True, null=True)),
                ("serial_numbers", models.JSONField(blank=True, default=list)),
                ("budget_item_id", models.IntegerField(blank=True, null=True)),
                ("budget_line_id", models.IntegerField(blank=True, null=True)),
                ("budget_reversed", models.BooleanField(default=False)),
                ("budget_reversal_date", models.DateTimeField(blank=True, null=True)),
                (
                    "movement_event_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Negative movement event created for this return",
                        null=True,
                    ),
                ),
                ("line_notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "goods_receipt_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_return_lines",
                        to="inventory.goodsreceiptline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "rtv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.returntovendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return To Vendor Line",
                "verbose_name_plural": "Return To Vendor Lines",
                "ordering": ["rtv", "id"],
                "indexes": [
                    models.Index(
                        fields=["company", "rtv"], name="inventory_r_company_1a781a_idx"
                    ),
                    models.Index(
                        fields=["product"], name="inventory_r_product_f858a2_idx"
                    ),
                    models.Index(
                        fields=["goods_receipt_line"],
                        name="inventory_r_goods_r_7c3037_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="returntovendor",
            index=models.Index(
                fields=["company", "rtv_number"], name="inventory_r_company_c0d54a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returntovendor",
            index=models.Index(
                fields=["goods_receipt", "status"],
                name="inventory_r_goods_r_8cb3aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="returntovendor",
            index=models.Index(
                fields=["status", "-rtv_date"], name="inventory_r_status_962b6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returntovendor",
            index=models.Index(
                fields=["posted_to_gl", "-rtv_date"],
                name="inventory_r_posted__bba558_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostvoucher",
            index=models.Index(
                fields=["company", "voucher_number"],
                name="inventory_l_company_5b5584_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostvoucher",
            index=models.Index(
                fields=["status", "-voucher_date"], name="inventory_l_status_ace443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostvoucher",
            index=models.Index(
                fields=["posted_to_gl", "-voucher_date"],
                name="inventory_l_posted__d7937a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostallocation",
            index=models.Index(
                fields=["company", "voucher"], name="inventory_l_company_553c48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostallocation",
            index=models.Index(
                fields=["goods_receipt", "status"],
                name="inventory_l_goods_r_17c938_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostallocation",
            index=models.Index(
                fields=["cost_layer"], name="inventory_l_cost_la_c3d558_idx"
            ),
        ),
    ]
