# Generated by Django 4.2.13 on 2025-11-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0030_unified_item_master"),
        ("inventory", "10025_materialissue_materialissueline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchlot",
            name="item",
        ),
        migrations.RemoveField(
            model_name="serialnumber",
            name="item",
        ),
        migrations.RemoveField(
            model_name="stockhold",
            name="item",
        ),
        migrations.AlterField(
            model_name="batchlot",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Master item record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batch_lots",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AlterField(
            model_name="serialnumber",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Master item record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="serial_numbers",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AlterField(
            model_name="stockhold",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Master item record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_holds",
                to="budgeting.budgetitemcode",
            ),
        ),
    ]
