# Generated by Django 4.2.13 on 2025-11-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("budgeting", "0030_unified_item_master"),
        ("inventory", "10026_unified_item_master"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="costlayer",
            name="inventory_c_company_1b2df0_idx",
        ),
        migrations.RemoveIndex(
            model_name="costlayer",
            name="inventory_c_company_b24896_idx",
        ),
        migrations.RemoveIndex(
            model_name="costlayer",
            name="inventory_c_company_abb635_idx",
        ),
        migrations.RemoveIndex(
            model_name="intransitshipmentline",
            name="inventory_i_company_cabb19_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemfefoconfig",
            name="inventory_i_company_7e4b7d_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemsupplier",
            name="inventory_i_company_a6f1f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemuomconversion",
            name="inventory_i_company_a0f9db_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemuomconversion",
            name="inventory_i_company_8116e9_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemvaluationmethod",
            name="inventory_i_company_768953_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemvaluationmethod",
            name="inventory_i_company_d241fc_idx",
        ),
        migrations.RemoveIndex(
            model_name="itemwarehouseconfig",
            name="inventory_i_company_bc0433_idx",
        ),
        migrations.RemoveIndex(
            model_name="landedcostlineapportionment",
            name="inventory_l_company_df3f49_idx",
        ),
        migrations.RemoveIndex(
            model_name="movementevent",
            name="inventory_m_company_5e6368_idx",
        ),
        migrations.RemoveIndex(
            model_name="purchasepricevariance",
            name="inventory_p_company_0d0d04_idx",
        ),
        migrations.RemoveIndex(
            model_name="returntovendorline",
            name="inventory_r_product_f858a2_idx",
        ),
        migrations.RemoveIndex(
            model_name="standardcostvariance",
            name="inventory_s_company_b194bf_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockledger",
            name="inventory_s_company_353bf4_idx",
        ),
        migrations.RemoveIndex(
            model_name="stocklevel",
            name="inventory_s_company_8cdc92_idx",
        ),
        migrations.RemoveIndex(
            model_name="valuationchangelog",
            name="inventory_v_company_79c5e8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="itemvaluationmethod",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="stocklevel",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="costlayer",
            name="product",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptline",
            name="item",
        ),
        migrations.RemoveField(
            model_name="intransitshipmentline",
            name="item",
        ),
        migrations.RemoveField(
            model_name="itemoperationalextension",
            name="item",
        ),
        migrations.RemoveField(
            model_name="landedcostallocation",
            name="product",
        ),
        migrations.RemoveField(
            model_name="landedcostlineapportionment",
            name="product",
        ),
        migrations.RemoveField(
            model_name="movementevent",
            name="item",
        ),
        migrations.RemoveField(
            model_name="purchasepricevariance",
            name="product",
        ),
        migrations.RemoveField(
            model_name="returntovendorline",
            name="product",
        ),
        migrations.RemoveField(
            model_name="standardcostvariance",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stockledger",
            name="item",
        ),
        migrations.RemoveField(
            model_name="stockmovementline",
            name="item",
        ),
        migrations.RemoveField(
            model_name="valuationchangelog",
            name="product",
        ),
        migrations.AddField(
            model_name="costlayer",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item for cost layer tracking",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_layers",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item being received",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipt_lines",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="intransitshipmentline",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item in transit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="in_transit_lines",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="itemvaluationmethod",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item for valuation tracking",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="valuation_methods",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="landedcostallocation",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item for landed cost voucher line",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="landed_cost_voucher_lines",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="landedcostlineapportionment",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item receiving landed cost allocation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="landed_cost_components",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="movementevent",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item for movement event",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movement_events",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="purchasepricevariance",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item with purchase price variance",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ppv_records",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="standardcostvariance",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item with standard cost variance",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="standard_variances",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="stockledger",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item for stock tracking",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_ledger_entries",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item with stock level",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_levels",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="stockmovementline",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item being moved",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movement_lines",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="valuationchangelog",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item with valuation change",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="valuation_changes",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemvaluationmethod",
            unique_together={("company", "budget_item", "warehouse", "effective_date")},
        ),
        migrations.AlterUniqueTogether(
            name="stocklevel",
            unique_together={("company", "budget_item", "warehouse")},
        ),
        migrations.AddIndex(
            model_name="costlayer",
            index=models.Index(
                fields=["company", "budget_item", "warehouse", "is_closed"],
                name="inventory_c_company_038336_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costlayer",
            index=models.Index(
                fields=["company", "budget_item", "warehouse", "fifo_sequence"],
                name="inventory_c_company_ad865e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costlayer",
            index=models.Index(
                fields=["company", "budget_item", "warehouse", "stock_state"],
                name="inventory_c_company_ab3241_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intransitshipmentline",
            index=models.Index(
                fields=["company", "budget_item"], name="inventory_i_company_4bc473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemfefoconfig",
            index=models.Index(
                fields=["company", "budget_item"], name="inventory_i_company_a0d166_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemsupplier",
            index=models.Index(
                fields=["company", "budget_item"], name="inventory_i_company_f31ddd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemuomconversion",
            index=models.Index(
                fields=["company", "budget_item", "effective_date"],
                name="inventory_i_company_70c737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemuomconversion",
            index=models.Index(
                fields=["company", "budget_item", "from_uom", "to_uom"],
                name="inventory_i_company_446af9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemvaluationmethod",
            index=models.Index(
                fields=["company", "budget_item", "warehouse", "-effective_date"],
                name="inventory_i_company_f47606_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemvaluationmethod",
            index=models.Index(
                fields=["company", "budget_item", "is_active"],
                name="inventory_i_company_34369c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemwarehouseconfig",
            index=models.Index(
                fields=["company", "budget_item", "reorder_point"],
                name="inventory_i_company_529cb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostlineapportionment",
            index=models.Index(
                fields=["company", "budget_item"], name="inventory_l_company_4c5e05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movementevent",
            index=models.Index(
                fields=["company", "budget_item", "warehouse"],
                name="inventory_m_company_0ef103_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasepricevariance",
            index=models.Index(
                fields=["company", "budget_item", "warehouse"],
                name="inventory_p_company_05197e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="returntovendorline",
            index=models.Index(
                fields=["budget_item"], name="inventory_r_budget__2c7a7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standardcostvariance",
            index=models.Index(
                fields=["company", "budget_item", "warehouse"],
                name="inventory_s_company_783631_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(
                fields=["company", "budget_item", "warehouse"],
                name="inventory_s_company_e9fe8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(
                fields=["company", "budget_item", "warehouse"],
                name="inventory_s_company_1078d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="valuationchangelog",
            index=models.Index(
                fields=["company", "budget_item", "warehouse"],
                name="inventory_v_company_42bf45_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="itemvaluationmethod",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stocklevel",
            name="item",
        ),
    ]
