# Generated by Django 4.2.13 on 2025-11-11 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("projects", "0001_initial"),
        ("budgeting", "0028_line_workflow_backfill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "10024_grn_serial_batch_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.CharField(max_length=50, unique=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Issue to Production"),
                            ("DEPARTMENT", "Issue to Department"),
                            ("SALES_ORDER", "Issue to Sales Order"),
                            ("PROJECT", "Issue to Project"),
                            ("COST_CENTER", "Issue to Cost Center"),
                            ("SAMPLE", "Sample Issue"),
                            ("OTHER", "Other"),
                        ],
                        default="DEPARTMENT",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("ISSUED", "Issued"),
                            ("PARTIALLY_RETURNED", "Partially Returned"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department name if not linked to cost center",
                        max_length=200,
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "purpose",
                    models.TextField(help_text="Purpose/reason for material issue"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Store keeper who issued the materials",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_issues",
                        to="inventory.internalrequisition",
                    ),
                ),
                (
                    "stock_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_issue_ref",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_material_issue",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialIssueLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "quantity_issued",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "serial_numbers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Serial numbers issued (for serialized items)",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per unit at time of issue",
                        max_digits=15,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost of this line",
                        max_digits=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Batch allocated for this issue",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issue_lines",
                        to="inventory.batchlot",
                    ),
                ),
                (
                    "budget_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_issue_lines",
                        to="budgeting.budgetitemcode",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issue_lines",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_issue_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "material_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.materialissue",
                    ),
                ),
                (
                    "movement_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_issue_line_ref",
                        to="inventory.movementevent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issue_lines",
                        to="projects.project",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issue_lines",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_material_issue_line",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["material_issue", "budget_item"],
                        name="inventory_m_materia_630912_idx",
                    ),
                    models.Index(
                        fields=["company", "budget_item"],
                        name="inventory_m_company_059d47_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="materialissue",
            index=models.Index(
                fields=["company", "status"], name="inventory_m_company_94ef10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialissue",
            index=models.Index(
                fields=["warehouse", "issue_date"],
                name="inventory_m_warehou_33f68c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialissue",
            index=models.Index(
                fields=["cost_center", "issue_date"],
                name="inventory_m_cost_ce_0c8be4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialissue",
            index=models.Index(
                fields=["issue_number"], name="inventory_m_issue_n_f6aaf6_idx"
            ),
        ),
    ]
