# Generated by Django 4.2.13 on 2025-11-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10027_item_to_budget_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehousebin",
            name="code",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
