# Generated by Django 4.2.13 on 2025-11-10 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "10019_remove_item_inventory_item_company_budget_item_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandedCostComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("FREIGHT", "Freight / Shipping"),
                            ("INSURANCE", "Insurance"),
                            ("CUSTOMS_DUTY", "Customs Duty"),
                            ("IMPORT_TAX", "Import Tax"),
                            ("BROKERAGE", "Brokerage Fees"),
                            ("PORT_HANDLING", "Port Handling"),
                            ("DEMURRAGE", "Demurrage"),
                            ("INSPECTION", "Inspection Fees"),
                            ("OTHER", "Other Charges"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount for this component",
                        max_digits=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "apportionment_method",
                    models.CharField(
                        choices=[
                            ("QUANTITY", "By Quantity"),
                            ("VALUE", "By Line Value"),
                            ("WEIGHT", "By Weight"),
                            ("VOLUME", "By Volume"),
                            ("MANUAL", "Manual Allocation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "apportioned_to_inventory",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount applied to remaining inventory",
                        max_digits=20,
                    ),
                ),
                (
                    "apportioned_to_cogs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount applied to consumed goods",
                        max_digits=20,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("supplier_id", models.IntegerField(blank=True, null=True)),
                (
                    "je_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Journal Entry ID for landed cost posting",
                        null=True,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False)),
                ("gl_posted_date", models.DateTimeField(blank=True, null=True)),
                ("applied_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_landed_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landed_cost_components",
                        to="inventory.goodsreceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landed Cost Component",
                "verbose_name_plural": "Landed Cost Components",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StandardCostVariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("GRN", "Goods Receipt"),
                            ("ISSUE", "Stock Issue"),
                            ("ADJUSTMENT", "Inventory Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(help_text="GRN ID or Stock Ledger ID"),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Standard cost per unit",
                        max_digits=15,
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Actual cost per unit",
                        max_digits=15,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity (stock UoM)",
                        max_digits=15,
                    ),
                ),
                (
                    "variance_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Actual - Standard (negative = favorable)",
                        max_digits=15,
                    ),
                ),
                (
                    "total_variance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="variance_per_unit × quantity",
                        max_digits=20,
                    ),
                ),
                (
                    "variance_type",
                    models.CharField(
                        choices=[
                            ("FAVORABLE", "Favorable (Actual < Standard)"),
                            ("UNFAVORABLE", "Unfavorable (Actual > Standard)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "variance_je_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Journal Entry ID for variance posting",
                        null=True,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False)),
                ("gl_posted_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_variances",
                        to="inventory.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_variances",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Cost Variance",
                "verbose_name_plural": "Standard Cost Variances",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "product", "warehouse"],
                        name="inventory_s_company_b194bf_idx",
                    ),
                    models.Index(
                        fields=["transaction_date", "variance_type"],
                        name="inventory_s_transac_1634b8_idx",
                    ),
                    models.Index(
                        fields=["posted_to_gl", "transaction_date"],
                        name="inventory_s_posted__fd7700_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchasePriceVariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "po_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Purchase Order unit price",
                        max_digits=15,
                    ),
                ),
                (
                    "invoice_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Actual invoice unit price",
                        max_digits=15,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, help_text="Quantity received", max_digits=15
                    ),
                ),
                (
                    "variance_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Invoice - PO (negative = favorable)",
                        max_digits=15,
                    ),
                ),
                (
                    "total_variance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="variance_per_unit × quantity",
                        max_digits=20,
                    ),
                ),
                (
                    "variance_type",
                    models.CharField(
                        choices=[
                            ("FAVORABLE", "Favorable (Invoice < PO)"),
                            ("UNFAVORABLE", "Unfavorable (Invoice > PO)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "variance_je_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Journal Entry ID for PPV posting",
                        null=True,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False)),
                ("gl_posted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier_id",
                    models.IntegerField(
                        blank=True, help_text="Supplier reference", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_variances",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ppv_records",
                        to="inventory.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ppv_records",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Price Variance",
                "verbose_name_plural": "Purchase Price Variances",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "product", "warehouse"],
                        name="inventory_p_company_0d0d04_idx",
                    ),
                    models.Index(
                        fields=["goods_receipt", "variance_type"],
                        name="inventory_p_goods_r_d3362a_idx",
                    ),
                    models.Index(
                        fields=["posted_to_gl", "-created_at"],
                        name="inventory_p_posted__c155bb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LandedCostLineApportionment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basis_value",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Quantity, value, weight, or volume used for apportionment",
                        max_digits=20,
                    ),
                ),
                (
                    "allocation_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="% of total component allocated to this line",
                        max_digits=7,
                    ),
                ),
                (
                    "apportioned_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount allocated to this line",
                        max_digits=20,
                    ),
                ),
                (
                    "cost_per_unit_adjustment",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Per-unit cost increase from this component",
                        max_digits=15,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "goods_receipt_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landed_cost_apportionments",
                        to="inventory.goodsreceiptline",
                    ),
                ),
                (
                    "landed_cost_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_apportionments",
                        to="inventory.landedcostcomponent",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Landed Cost Line Apportionment",
                "verbose_name_plural": "Landed Cost Line Apportionments",
                "ordering": ["landed_cost_component", "goods_receipt_line"],
                "indexes": [
                    models.Index(
                        fields=["company", "product"],
                        name="inventory_l_company_df3f49_idx",
                    ),
                    models.Index(
                        fields=["landed_cost_component"],
                        name="inventory_l_landed__1e9a67_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="landedcostcomponent",
            index=models.Index(
                fields=["company", "goods_receipt"],
                name="inventory_l_company_e77eda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostcomponent",
            index=models.Index(
                fields=["component_type", "-created_at"],
                name="inventory_l_compone_d70ee5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landedcostcomponent",
            index=models.Index(
                fields=["posted_to_gl"], name="inventory_l_posted__ee8ca4_idx"
            ),
        ),
    ]
