# Generated by Django 4.2.13 on 2025-11-11 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("sales", "0007_fix_salesorderline_to_sales_product"),
        ("budgeting", "0028_line_workflow_backfill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "10022_remove_returntovendorline_budget_item_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_lot_number",
                    models.CharField(
                        blank=True, help_text="Supplier's batch/lot ID", max_length=100
                    ),
                ),
                (
                    "internal_batch_code",
                    models.CharField(
                        help_text="Auto-generated or manual internal code",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "mfg_date",
                    models.DateField(
                        blank=True, help_text="Manufacture date", null=True
                    ),
                ),
                (
                    "exp_date",
                    models.DateField(
                        blank=True, help_text="Expiration/use-by date", null=True
                    ),
                ),
                ("received_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Original received quantity in stock UoM",
                        max_digits=15,
                    ),
                ),
                (
                    "current_qty",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Remaining quantity after issuances",
                        max_digits=15,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost of this batch",
                        max_digits=20,
                    ),
                ),
                (
                    "certificate_of_analysis",
                    models.FileField(blank=True, null=True, upload_to="coa/"),
                ),
                ("coa_upload_date", models.DateField(blank=True, null=True)),
                ("storage_location", models.CharField(blank=True, max_length=200)),
                ("hazmat_classification", models.CharField(blank=True, max_length=50)),
                (
                    "hold_status",
                    models.CharField(
                        choices=[
                            ("QUARANTINE", "Quarantine"),
                            ("ON_HOLD", "On Hold"),
                            ("RELEASED", "Released"),
                            ("SCRAP", "Scrap"),
                        ],
                        default="QUARANTINE",
                        max_length=20,
                    ),
                ),
                (
                    "fefo_sequence",
                    models.IntegerField(
                        default=0, help_text="For FEFO sorting (lower = pick first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_lots",
                        to="budgeting.budgetitemcode",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_lots",
                        to="companies.company",
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_lots",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_lots",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_batch_lot",
            },
        ),
        migrations.CreateModel(
            name="QCCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkpoint_name",
                    models.CharField(
                        help_text="e.g., Receiving Dock Inspection", max_length=200
                    ),
                ),
                (
                    "checkpoint_order",
                    models.PositiveIntegerField(default=1, help_text="Sequence order"),
                ),
                (
                    "automatic_after",
                    models.BooleanField(
                        default=False, help_text="Auto-run without user intervention"
                    ),
                ),
                (
                    "inspection_criteria",
                    models.TextField(help_text="What to check during inspection"),
                ),
                (
                    "inspection_template",
                    models.CharField(
                        blank=True, help_text="SOP document ID or URL", max_length=200
                    ),
                ),
                (
                    "acceptance_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=95.0,
                        help_text="AQL level (percentage)",
                        max_digits=5,
                    ),
                ),
                (
                    "escalation_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Reject % to escalate",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_checkpoints_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_checkpoints",
                        to="companies.company",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_checkpoints",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_qc_checkpoint",
                "ordering": ["checkpoint_order"],
            },
        ),
        migrations.CreateModel(
            name="StockHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hold_type",
                    models.CharField(
                        choices=[
                            ("QC_INSPECTION", "QC Inspection"),
                            ("DOCUMENT_HOLD", "Document Hold"),
                            ("APPROVAL_PENDING", "Approval Pending"),
                            ("CUSTOMER_RETURN", "Customer Return"),
                            ("DEFECT", "Defect"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "qty_held",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity held in stock UoM",
                        max_digits=15,
                    ),
                ),
                ("hold_reason", models.TextField(help_text="Detailed reason for hold")),
                ("hold_date", models.DateField(default=django.utils.timezone.now)),
                ("expected_release_date", models.DateField(blank=True, null=True)),
                ("actual_release_date", models.DateField(blank=True, null=True)),
                (
                    "qc_pass_result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("PENDING", "Pending"),
                            ("CONDITIONAL", "Conditional"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("qc_notes", models.TextField(blank=True)),
                (
                    "escalation_flag",
                    models.BooleanField(
                        default=False, help_text="Set if hold is overdue"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RELEASED", "Released"),
                            ("SCRAPPED", "Scrapped"),
                            ("RETURNED", "Returned"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TO_WAREHOUSE", "Move to Warehouse"),
                            ("SCRAP", "Scrap"),
                            ("RETURN", "Return to Supplier"),
                            ("REWORK", "Rework"),
                            ("REJECT", "Reject"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_holds",
                        to="inventory.batchlot",
                    ),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_holds",
                        to="inventory.warehousebin",
                    ),
                ),
                (
                    "budget_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_holds",
                        to="budgeting.budgetitemcode",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_holds",
                        to="companies.company",
                    ),
                ),
                (
                    "hold_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holds_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_holds",
                        to="inventory.item",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holds_released",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_holds",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stock_hold",
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="inventory_s_company_b1b685_idx",
                    ),
                    models.Index(
                        fields=["warehouse", "status"],
                        name="inventory_s_warehou_2dea9a_idx",
                    ),
                    models.Index(
                        fields=["hold_date"], name="inventory_s_hold_da_3632aa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SerialNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Unique serial number per item", max_length=200
                    ),
                ),
                ("warranty_start", models.DateField(blank=True, null=True)),
                ("warranty_end", models.DateField(blank=True, null=True)),
                (
                    "asset_tag",
                    models.CharField(
                        blank=True,
                        help_text="Fixed asset tag if applicable",
                        max_length=100,
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                (
                    "issued_to",
                    models.CharField(
                        blank=True, help_text="Customer/Department", max_length=200
                    ),
                ),
                ("received_back_date", models.DateField(blank=True, null=True)),
                ("inspection_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "In Stock"),
                            ("ASSIGNED", "Assigned to Order"),
                            ("ISSUED", "Issued"),
                            ("RETURNED", "Returned"),
                            ("SCRAPPED", "Scrapped"),
                        ],
                        default="IN_STOCK",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to_customer_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_serials",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "batch_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serial_numbers",
                        to="inventory.batchlot",
                    ),
                ),
                (
                    "budget_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serial_numbers",
                        to="budgeting.budgetitemcode",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serial_numbers",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serial_numbers",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_serial_number",
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="inventory_s_company_cf8187_idx",
                    ),
                    models.Index(
                        fields=["serial_number"], name="inventory_s_serial__b9c4b1_idx"
                    ),
                ],
                "unique_together": {("budget_item", "serial_number")},
            },
        ),
        migrations.CreateModel(
            name="QCResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspected_date", models.DateField(default=django.utils.timezone.now)),
                ("qty_inspected", models.DecimalField(decimal_places=3, max_digits=15)),
                ("qty_accepted", models.DecimalField(decimal_places=3, max_digits=15)),
                ("qty_rejected", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAMAGE", "Damage"),
                            ("INCOMPLETE_DOC", "Incomplete Documentation"),
                            ("WRONG_ITEM", "Wrong Item"),
                            ("QUANTITY_DISCREPANCY", "Quantity Discrepancy"),
                            ("QUALITY_ISSUE", "Quality Issue"),
                            ("EXPIRY_ISSUE", "Expiry/Date Issue"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "qc_status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL_PASS", "Conditional Pass"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "rework_instruction",
                    models.TextField(
                        blank=True, help_text="Instructions if conditional pass"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="qc_attachments/"
                    ),
                ),
                (
                    "hold_created",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this result created a stock hold",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_results",
                        to="inventory.qccheckpoint",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_results",
                        to="companies.company",
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_results",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_qc_result",
                "indexes": [
                    models.Index(
                        fields=["company", "inspected_date"],
                        name="inventory_q_company_027d6b_idx",
                    ),
                    models.Index(fields=["grn"], name="inventory_q_grn_id_b6fca9_idx"),
                    models.Index(
                        fields=["qc_status"], name="inventory_q_qc_stat_57903e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="qccheckpoint",
            index=models.Index(
                fields=["company", "warehouse"], name="inventory_q_company_bde5f3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qccheckpoint",
            unique_together={("warehouse", "checkpoint_name")},
        ),
        migrations.AddIndex(
            model_name="batchlot",
            index=models.Index(
                fields=["company", "hold_status"], name="inventory_b_company_c3acf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchlot",
            index=models.Index(
                fields=["budget_item", "exp_date"],
                name="inventory_b_budget__8e0f83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="batchlot",
            index=models.Index(
                fields=["internal_batch_code"], name="inventory_b_interna_8de244_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchlot",
            index=models.Index(
                fields=["fefo_sequence"], name="inventory_b_fefo_se_4e6b15_idx"
            ),
        ),
    ]
