# Generated by Django 4.2.13 on 2025-11-12 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgeting", "0031_unified_item_production"),
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("inventory", "10029_auto_generate_item_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseOverrideLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        help_text="Type of transaction (GRN, Material Issue, Transfer, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.IntegerField(help_text="ID of the related transaction"),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        blank=True,
                        help_text="Transaction number for easy reference",
                        max_length=100,
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(help_text="Reason provided by user"),
                ),
                (
                    "warning_level",
                    models.CharField(
                        help_text="Warning level at time of override", max_length=20
                    ),
                ),
                (
                    "was_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether supervisor approval was obtained",
                    ),
                ),
                ("overridden_at", models.DateTimeField(auto_now_add=True)),
                (
                    "was_valid_override",
                    models.BooleanField(
                        blank=True,
                        help_text="Reviewed by manager - was this a valid override?",
                        null=True,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_warehouse",
                    models.ForeignKey(
                        help_text="User-selected warehouse",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_overrides",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_warehouse_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_overrides",
                        to="budgeting.budgetitemcode",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this override belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_overrides",
                        to="companies.company",
                    ),
                ),
                (
                    "item_category",
                    models.ForeignKey(
                        help_text="Category at time of override",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="inventory.itemcategory",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewed_warehouse_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggested_warehouse",
                    models.ForeignKey(
                        help_text="System-suggested warehouse",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_overrides",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse Override Log",
                "verbose_name_plural": "Warehouse Override Logs",
                "db_table": "inventory_warehouse_override_log",
                "ordering": ["-overridden_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "overridden_at"],
                        name="inventory_w_company_54a6bd_idx",
                    ),
                    models.Index(
                        fields=["overridden_by", "overridden_at"],
                        name="inventory_w_overrid_2a3bcd_idx",
                    ),
                    models.Index(
                        fields=["budget_item", "overridden_at"],
                        name="inventory_w_budget__ab3778_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "transaction_id"],
                        name="inventory_w_transac_dfe14c_idx",
                    ),
                    models.Index(
                        fields=["was_valid_override"],
                        name="inventory_w_was_val_d477ee_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseCategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-select this warehouse for items in this category",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Priority when multiple warehouses match (higher = preferred)",
                    ),
                ),
                (
                    "allow_multi_warehouse",
                    models.BooleanField(
                        default=False,
                        help_text="Items in this category can be stored in multiple warehouses without warnings",
                    ),
                ),
                (
                    "warning_level",
                    models.CharField(
                        choices=[
                            ("INFO", "Informational - can proceed without reason"),
                            ("WARNING", "Warning - requires reason"),
                            ("CRITICAL", "Critical - requires supervisor approval"),
                        ],
                        default="WARNING",
                        help_text="Warning level when user selects different warehouse",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this mapping"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Item category (required)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_mappings",
                        to="inventory.itemcategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this mapping belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_category_mappings",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific subcategory (optional - leave blank for all subcategories)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_subcategory_mappings",
                        to="inventory.itemcategory",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Warehouse for this category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_mappings",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse Category Mapping",
                "verbose_name_plural": "Warehouse Category Mappings",
                "db_table": "inventory_warehouse_category_mapping",
                "ordering": ["-priority", "warehouse__name"],
                "indexes": [
                    models.Index(
                        fields=["company", "category", "subcategory"],
                        name="inventory_w_company_3434c5_idx",
                    ),
                    models.Index(
                        fields=["warehouse", "is_default"],
                        name="inventory_w_warehou_c8baeb_idx",
                    ),
                    models.Index(
                        fields=["category", "is_default"],
                        name="inventory_w_categor_77792d_idx",
                    ),
                ],
                "unique_together": {
                    ("company", "warehouse", "category", "subcategory")
                },
            },
        ),
    ]
