# Generated by Django 4.2.7 on 2025-10-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("hr", "0002_department_employeeleavebalance_employmentgrade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeeleavebalance",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employmentgrade",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leavetype",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payrollline",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
    ]
