# Generated by Django 4.2.7 on 2025-10-30 07:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("budgeting", "0005_alter_budgetusage_usage_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0003_department_company_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "rate_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.50"),
                        help_text="Multiplier applied on employee base overtime rate.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "fixed_hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Override rate. If set, multiplier is ignored.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "auto_apply_budget",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically link approved entries to the default budget line.",
                    ),
                ),
                (
                    "max_hours_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("4.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_hours_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("24.00"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "qa_review_required",
                    models.BooleanField(
                        default=False,
                        help_text="If true, QA team must flag completion before payroll uses the overtime.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        help_text="Company group this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.companygroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_budget_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_policies",
                        to="budgeting.budgetline",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_policies",
                        to="hr.department",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_policies",
                        to="hr.employmentgrade",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DAY", "Day"),
                            ("NIGHT", "Night"),
                            ("ROTATING", "Rotating"),
                            ("FLEX", "Flexible"),
                        ],
                        default="DAY",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "default_headcount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Target crew size for this shift before overtime.",
                    ),
                ),
                ("allow_overtime", models.BooleanField(default=True)),
                ("color_hex", models.CharField(default="#1677ff", max_length=7)),
                ("is_night_shift", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        help_text="Company group this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.companygroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_overtime_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_shifts",
                        to="hr.overtimepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="gps_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="gps_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="source_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="employee",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="OvertimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("ATTENDANCE", "Attendance Sync"),
                            ("CAPACITY_PLAN", "Capacity Planner"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "requested_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "approved_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "qa_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Marked when QA requires follow-up on this overtime session.",
                    ),
                ),
                ("qa_notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_to_payroll", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_overtime_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_entries",
                        to="budgeting.budgetline",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        help_text="Company group this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.companygroup",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_entries",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overtime_entries",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_entries",
                        to="hr.payrollrun",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_entries",
                        to="hr.overtimepolicy",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_entries",
                        to="hr.shifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="hr.shifttemplate",
            ),
        ),
        migrations.CreateModel(
            name="WorkforceCapacityPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production"),
                            ("SERVICE", "Service"),
                            ("SUPPORT", "Support"),
                        ],
                        default="PRODUCTION",
                        max_length=20,
                    ),
                ),
                ("required_headcount", models.PositiveIntegerField(default=0)),
                ("qa_required_headcount", models.PositiveIntegerField(default=0)),
                (
                    "planned_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "target_utilization_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("85.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        help_text="Company group this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.companygroup",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_plans",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qa_cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qa_capacity_plans",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_plans",
                        to="hr.shifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "shift__start_time"],
                "indexes": [
                    models.Index(
                        fields=["company", "date"],
                        name="hr_workforc_company_1383d4_idx",
                    ),
                    models.Index(
                        fields=["company", "cost_center", "date"],
                        name="hr_workforc_company_fe37b8_idx",
                    ),
                ],
                "unique_together": {("company", "date", "shift", "cost_center")},
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("work_location", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        help_text="Company group this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.companygroup",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_assignments",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="hr.employee",
                    ),
                ),
                (
                    "overtime_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_assignments",
                        to="hr.overtimepolicy",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="hr.shifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("-effective_from",),
                "indexes": [
                    models.Index(
                        fields=["company", "employee", "effective_from"],
                        name="hr_shiftass_company_921a91_idx",
                    ),
                    models.Index(
                        fields=["company", "shift", "effective_from"],
                        name="hr_shiftass_company_9818f2_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="overtimepolicy",
            index=models.Index(
                fields=["company", "department"], name="hr_overtime_company_34aea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimepolicy",
            index=models.Index(
                fields=["company", "grade"], name="hr_overtime_company_c11123_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimepolicy",
            index=models.Index(
                fields=["company", "is_active"], name="hr_overtime_company_471f38_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="overtimepolicy",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="overtimeentry",
            index=models.Index(
                fields=["company", "date"], name="hr_overtime_company_d20a50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimeentry",
            index=models.Index(
                fields=["company", "employee", "date"],
                name="hr_overtime_company_d10867_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="overtimeentry",
            index=models.Index(
                fields=["company", "status"], name="hr_overtime_company_7786f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimeentry",
            index=models.Index(
                fields=["company", "posted_to_payroll"],
                name="hr_overtime_company_626bc2_idx",
            ),
        ),
    ]
