# Generated by Django 4.2.7 on 2025-10-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this database connection",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("django.db.backends.postgresql", "PostgreSQL"),
                            ("django.db.backends.mysql", "MySQL"),
                            ("django.db.backends.oracle", "Oracle"),
                            ("django.db.backends.sqlite3", "SQLite (External)"),
                        ],
                        help_text="Database engine to use",
                        max_length=100,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="Database host (e.g., localhost, IP address)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True,
                        help_text="Database port (e.g., 5432 for PostgreSQL)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        blank=True,
                        help_text="Database username",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Database password",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "db_name",
                    models.CharField(help_text="Name of the database", max_length=100),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this connection active and available for use?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Database Connection",
                "verbose_name_plural": "Database Connections",
            },
        ),
    ]
