# Generated by Django 4.2.7 on 2025-10-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0003_companygroup_remove_company_external_db_connection_and_more",
        ),
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DatabaseConnection",
        ),
    ]
