# Generated by Django 4.2.13 on 2025-11-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_fix_workordercomponent_materialissueline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialissueline",
            options={"ordering": ("issue", "item__code")},
        ),
    ]
