# Generated by Django 4.2.13 on 2025-11-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0031_unified_item_production"),
        ("production", "0004_alter_materialissueline_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterial",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boms",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterialcomponent",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bom_components",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AlterField(
            model_name="materialissueline",
            name="item",
            field=models.ForeignKey(
                help_text="Item being issued for production",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="material_issue_lines",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AlterField(
            model_name="workordercomponent",
            name="component",
            field=models.ForeignKey(
                help_text="Component item required for production",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_order_components",
                to="budgeting.budgetitemcode",
            ),
        ),
    ]
