# Generated by Django 4.2.7 on 2025-10-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True)),
                ("definition", models.JSONField(blank=True, default=dict)),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("CORE", "Core System"),
                            ("INDUSTRY_PACK", "Industry Pack Baseline"),
                            ("GROUP_CUSTOM", "Group Customization"),
                            ("COMPANY_OVERRIDE", "Company Override"),
                        ],
                        default="COMPANY_OVERRIDE",
                        max_length=20,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company"),
                            ("GROUP", "Company Group"),
                            ("GLOBAL", "Global"),
                        ],
                        default="COMPANY",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_templates",
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_templates",
                        to="companies.companygroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_instances",
                        to="companies.company",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflows.workflowtemplate",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["company", "status"], name="workflows_w_company_09a55c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "COMPANY")),
                fields=("slug", "company"),
                name="uniq_workflow_company_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GROUP")),
                fields=("slug", "company_group"),
                name="uniq_workflow_group_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GLOBAL")),
                fields=("slug",),
                name="uniq_workflow_global_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["company", "state"], name="workflows_w_company_a39965_idx"
            ),
        ),
    ]
