# Generated by Django 4.2.7 on 2025-10-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("metadata", "0002_alter_metadatadefinition_options_and_more"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowtemplate",
            name="workflows_w_company_4c9b9e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="workflowtemplate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_templates",
                to="companies.companygroup",
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="layer",
            field=models.CharField(
                choices=[
                    ("CORE", "Core System"),
                    ("INDUSTRY_PACK", "Industry Pack Baseline"),
                    ("GROUP_CUSTOM", "Group Customization"),
                    ("COMPANY_OVERRIDE", "Company Override"),
                ],
                default="COMPANY_OVERRIDE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="metadata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_versions",
                to="metadata.metadatadefinition",
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Company"),
                    ("GROUP", "Company Group"),
                    ("GLOBAL", "Global"),
                ],
                default="COMPANY",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["company", "status"], name="workflows_w_company_09a55c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "COMPANY")),
                fields=("slug", "company"),
                name="uniq_workflow_company_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GROUP")),
                fields=("slug", "company_group"),
                name="uniq_workflow_group_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GLOBAL")),
                fields=("slug",),
                name="uniq_workflow_global_slug",
            ),
        ),
        migrations.RemoveField(
            model_name="workflowtemplate",
            name="is_active",
        ),
    ]
