# Generated by Django 4.2.13 on 2025-11-05 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflows", "0002_approver_routing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstance",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only this user may act on the instance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_workflow_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
