from django.urls import path
from .views import (
    AIAlertUnreadCountView,
    AIChatView,
    AIConversationHistoryView,
    AIFeedbackView,
    AIStatusView,
    AISuggestionListView,
    AITrainView,
    AITrainingExampleDetailView,
    AITrainingExampleListView,
    AITrainingExampleBulkUpdateView,
    AILoRARunView,
    AIPreferenceListCreateView,
    AIPreferenceDetailView,
    AIActionExecuteView,
    AIWorkflowExplainView,
    AIMetadataInterestView,
    AIOpsMetricsView,
)

urlpatterns = [
    path('status/', AIStatusView.as_view()),
    path('chat/', AIChatView.as_view()),
    path('feedback/', AIFeedbackView.as_view()),
    path('train/', AITrainView.as_view()),
    path('suggestions/', AISuggestionListView.as_view()),
    path('alerts/unread-count/', AIAlertUnreadCountView.as_view()),
    path('conversations/history/', AIConversationHistoryView.as_view()),
    path('training-examples/', AITrainingExampleListView.as_view()),
    path('training-examples/<int:pk>/', AITrainingExampleDetailView.as_view()),
    path('training-examples/bulk/', AITrainingExampleBulkUpdateView.as_view()),
    path('ops/lora-runs/', AILoRARunView.as_view()),
    path('preferences/', AIPreferenceListCreateView.as_view()),
    path('preferences/<uuid:pk>/', AIPreferenceDetailView.as_view()),
    path('actions/', AIActionExecuteView.as_view()),
    path('metadata/interest/', AIMetadataInterestView.as_view()),
    path('workflows/explain/', AIWorkflowExplainView.as_view()),
    path('ops/metrics/', AIOpsMetricsView.as_view()),
]
