# Generated by Django 4.2.13 on 2025-11-01 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleFeatureToggle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        db_index=True,
                        help_text="Module identifier (e.g., 'finance', 'hr', 'inventory')",
                        max_length=100,
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(
                        db_index=True,
                        help_text="Feature identifier (e.g., 'journal_vouchers', 'sales_orders'). Use 'module' for entire module.",
                        max_length=100,
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        help_text="Human-readable feature name", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this feature does",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(blank=True, help_text="Help text for end users"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier (e.g., 'mdi-finance', 'fa-users')",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("beta", "Beta"),
                            ("deprecated", "Deprecated"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        default="enabled",
                        help_text="Feature status",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the feature is currently enabled",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the feature appears in menus (even if disabled)",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global (All Companies)"),
                            ("GROUP", "Company Group"),
                            ("COMPANY", "Specific Company"),
                        ],
                        db_index=True,
                        default="GLOBAL",
                        help_text="Scope of this feature toggle",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Feature-specific configuration parameters (JSON)",
                    ),
                ),
                (
                    "depends_on",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of required feature keys (e.g., ['finance.accounts', 'inventory.products'])",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Display priority (higher = shown first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company (required if scope_type=COMPANY)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_toggles",
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company group (required if scope_type=GROUP)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_toggles",
                        to="companies.companygroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_toggles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_feature_toggles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Toggle",
                "verbose_name_plural": "Feature Toggles",
                "db_table": "admin_feature_toggles",
                "ordering": ["-priority", "module_name", "feature_key"],
            },
        ),
        migrations.CreateModel(
            name="FeatureAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_toggle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="admin_settings.modulefeaturetoggle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feature_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Audit Log",
                "verbose_name_plural": "Feature Audit Logs",
                "db_table": "admin_feature_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="modulefeaturetoggle",
            index=models.Index(
                fields=["module_name", "feature_key", "scope_type"],
                name="admin_featu_module__164d38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modulefeaturetoggle",
            index=models.Index(
                fields=["is_enabled", "scope_type"],
                name="admin_featu_is_enab_b4e382_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modulefeaturetoggle",
            index=models.Index(
                fields=["company_group", "is_enabled"],
                name="admin_featu_company_b19503_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modulefeaturetoggle",
            index=models.Index(
                fields=["company", "is_enabled"], name="admin_featu_company_e06764_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modulefeaturetoggle",
            unique_together={
                ("module_name", "feature_key", "scope_type", "company_group", "company")
            },
        ),
        migrations.AddIndex(
            model_name="featureauditlog",
            index=models.Index(
                fields=["feature_toggle", "-timestamp"],
                name="admin_featu_feature_264f30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="featureauditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="admin_featu_user_id_0f447b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureauditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="admin_featu_action_81c461_idx"
            ),
        ),
    ]
