# Generated by Django 4.2.7 on 2025-10-30 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True)),
                ("layout", models.JSONField(blank=True, default=dict)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company"),
                            ("GROUP", "Company Group"),
                            ("GLOBAL", "Global"),
                        ],
                        default="COMPANY",
                        max_length=15,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("CORE", "Core System"),
                            ("INDUSTRY_PACK", "Industry Pack Baseline"),
                            ("GROUP_CUSTOM", "Group Customization"),
                            ("COMPANY_OVERRIDE", "Company Override"),
                        ],
                        default="COMPANY_OVERRIDE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_definitions",
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_definitions",
                        to="companies.companygroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidgetDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("widget_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboard.dashboarddefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
                "unique_together": {("dashboard", "key")},
            },
        ),
        migrations.CreateModel(
            name="DashboardLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layout", models.JSONField(blank=True, default=dict)),
                ("widgets", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_layouts",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_layout",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "company")},
            },
        ),
        migrations.AddConstraint(
            model_name="dashboarddefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "COMPANY")),
                fields=("slug", "company"),
                name="uniq_dashboard_company_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboarddefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GROUP")),
                fields=("slug", "company_group"),
                name="uniq_dashboard_group_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboarddefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GLOBAL")),
                fields=("slug",),
                name="uniq_dashboard_global_slug",
            ),
        ),
    ]
