# Generated by Django 4.2.7 on 2025-10-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0003_companygroup_remove_company_external_db_connection_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_groups",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="companies.companygroup"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_company_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_users",
                to="companies.companygroup",
            ),
        ),
        migrations.AddField(
            model_name="usercompanyrole",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
    ]
