# Generated by Django 4.2.13 on 2025-11-04 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_branch_department_departmentmembership_and_more"),
        ("users", "0003_user_admin_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOrganizationalAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_branches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="members_via_branch",
                        to="companies.branch",
                    ),
                ),
                (
                    "access_companies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="members_via_company",
                        to="companies.company",
                    ),
                ),
                (
                    "access_departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="members_via_department",
                        to="companies.department",
                    ),
                ),
                (
                    "access_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="members_via_group",
                        to="companies.companygroup",
                    ),
                ),
                (
                    "primary_branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default branch on login (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="companies.branch",
                    ),
                ),
                (
                    "primary_company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default company on login",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="companies.company",
                    ),
                ),
                (
                    "primary_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default department on login (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="companies.department",
                    ),
                ),
                (
                    "primary_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default group on login",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="companies.companygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Organizational Access",
                "verbose_name_plural": "User Organizational Access",
                "db_table": "user_organizational_access",
            },
        ),
    ]
