# Generated by Django 4.2.7 on 2025-10-30 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecPermission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the permission (e.g., procurement_create_pr)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        help_text="Category of the permission (e.g., finance, procurement)",
                        max_length=50,
                    ),
                ),
                (
                    "scope_required",
                    models.BooleanField(
                        default=False,
                        help_text="Does this permission require a specific scope (e.g., company, cost center)?",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Does this permission involve sensitive data or actions?",
                    ),
                ),
                (
                    "is_assignable",
                    models.BooleanField(
                        default=True,
                        help_text="Can this permission be assigned to roles by admins?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Security Permission",
                "verbose_name_plural": "Security Permissions",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="SecRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the role (e.g., Procurement Officer)",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the role (e.g., r_procurement_officer)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a system-defined role that cannot be modified by admins?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_roles",
                        to="companies.companygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Role",
                "verbose_name_plural": "Security Roles",
                "ordering": ["name"],
                "unique_together": {("code", "company_group")},
            },
        ),
        migrations.CreateModel(
            name="SecScope",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "scope_type",
                    models.CharField(
                        help_text="Type of scope (e.g., company, cost_center, branch)",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the actual object (e.g., Company.id, CostCenter.id)",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the scope (e.g., 'Company A', 'HR Department')",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_scopes",
                        to="companies.companygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Scope",
                "verbose_name_plural": "Security Scopes",
                "ordering": ["scope_type", "name"],
                "unique_together": {("scope_type", "object_id", "company_group")},
            },
        ),
        migrations.CreateModel(
            name="SecSoDRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "first_action_code",
                    models.CharField(
                        help_text="Permission code for the first action", max_length=100
                    ),
                ),
                (
                    "second_action_code",
                    models.CharField(
                        help_text="Permission code for the second action that cannot be performed by the same user",
                        max_length=100,
                    ),
                ),
                (
                    "enforcement",
                    models.CharField(
                        choices=[("BLOCK", "Block"), ("WARN", "Warn")],
                        default="BLOCK",
                        max_length=10,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Scope type for which this rule applies",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Segregation of Duties Rule",
                "verbose_name_plural": "Segregation of Duties Rules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecUserRole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_delegated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delegated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="security.secrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role Assignment",
                "verbose_name_plural": "User Role Assignments",
                "ordering": ["user__username", "role__name"],
                "unique_together": {("user", "role")},
            },
        ),
        migrations.CreateModel(
            name="SecUserRoleScope",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role_scopes",
                        to="security.secscope",
                    ),
                ),
                (
                    "user_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="security.secuserrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role Scope Assignment",
                "verbose_name_plural": "User Role Scope Assignments",
                "unique_together": {("user_role", "scope")},
            },
        ),
        migrations.CreateModel(
            name="SecUserDirectPermission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_user_permissions",
                        to="security.secpermission",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_user_permissions",
                        to="security.secscope",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Direct Permission",
                "verbose_name_plural": "User Direct Permissions",
                "unique_together": {("user", "permission", "scope")},
            },
        ),
        migrations.CreateModel(
            name="SecRolePermission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "amount_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: Amount limit for this permission within the role",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "percent_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: Percentage limit for this permission within the role",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional: JSON conditions for complex permission rules",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="security.secpermission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="security.secrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission Assignment",
                "verbose_name_plural": "Role Permission Assignments",
                "unique_together": {("role", "permission")},
            },
        ),
    ]
