# Generated by Django 4.2.7 on 2025-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("READ", "Read"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("PROVISION", "Provision"),
                    ("MIGRATE", "Migrate"),
                    ("OTHER", "Other"),
                    ("FORM_LAYOUT_CHANGED", "Form Layout Changed"),
                    ("FORM_FIELD_ADDED", "Form Field Added"),
                    ("CUSTOM_MODULE_CREATED", "Custom Module Created"),
                    ("WORKFLOW_CHANGED", "Workflow Changed"),
                    ("DASHBOARD_CHANGED", "Dashboard Definition Changed"),
                ],
                max_length=50,
            ),
        ),
    ]
