# Generated by Django 4.2.7 on 2025-10-28 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("ai_companion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aifeedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("thumbs", "Thumbs"),
                    ("review", "Structured Review"),
                    ("task", "Review Task"),
                ],
                default="thumbs",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="AITrainingExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("completion", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("feedback", "Feedback"),
                            ("curated", "Curated"),
                            ("telemetry", "Telemetry"),
                        ],
                        default="feedback",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="review",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_training_examples",
                        to="companies.company",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_examples",
                        to="ai_companion.aifeedback",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_training_examples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status"], name="ai_companio_status_7c5e47_idx"
                    ),
                    models.Index(
                        fields=["source"], name="ai_companio_source_0b3f19_idx"
                    ),
                    models.Index(
                        fields=["company", "status"],
                        name="ai_companio_company_d1e124_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AITelemetryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=120)),
                ("source", models.CharField(default="ai_companion", max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_telemetry_events",
                        to="companies.company",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_events",
                        to="ai_companion.aiconversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_telemetry_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_companio_user_id_eb433b_idx",
                    ),
                    models.Index(
                        fields=["company", "created_at"],
                        name="ai_companio_company_191e83_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="ai_companio_event_t_a548fd_idx"
                    ),
                ],
            },
        ),
    ]
