# Generated by Django 4.2.7 on 2025-10-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_companion", "0005_ai_trainingexample_review_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiguardrailtestcase",
            new_name="ai_companio_company_629f77_idx",
            old_name="ai_guardra_company_7375f1_idx",
        ),
        migrations.RenameIndex(
            model_name="aiguardrailtestcase",
            new_name="ai_companio_policy__fd0c1e_idx",
            old_name="ai_guardra_policy__974369_idx",
        ),
        migrations.RenameIndex(
            model_name="ailorarun",
            new_name="ai_companio_status_65bd12_idx",
            old_name="ai_loraru_status_4ee31b_idx",
        ),
        migrations.RenameIndex(
            model_name="ailorarun",
            new_name="ai_companio_adapter_a60c28_idx",
            old_name="ai_loraru_adapter_458b42_idx",
        ),
        migrations.RenameIndex(
            model_name="aitrainingexample",
            new_name="ai_companio_reviewe_1a387b_idx",
            old_name="ai_trainin_reviewe_83f33c_idx",
        ),
        migrations.AlterField(
            model_name="aiguardrailtestcase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ailorarun",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aimessage",
            name="intent",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
