# Generated by Django 4.2.7 on 2025-10-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
        (
            "ai_companion",
            "0006_rename_ai_guardra_company_7375f1_idx_ai_companio_company_629f77_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAIPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("value", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.CharField(blank=True, default="manual", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_preferences",
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_preferences",
                        to="companies.companygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "company", "key"],
                        name="ai_companio_user_id_965edc_idx",
                    ),
                    models.Index(
                        fields=["user", "key"], name="ai_companio_user_id_23f88b_idx"
                    ),
                ],
                "unique_together": {("user", "company", "key")},
            },
        ),
    ]
