# Generated by Django 4.2.7 on 2025-10-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_companion", "0007_useraipreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiproactivesuggestion",
            name="alert_type",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="aiproactivesuggestion",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                default="info",
                max_length=20,
            ),
        ),
    ]
