# Generated by Django 4.2.13 on 2025-10-31 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("ai_companion", "0009_aiactionexecution"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=100, unique=True),
                ),
                (
                    "ai_assistant_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable AI assistant globally",
                    ),
                ),
                (
                    "document_processing_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable AI document processing (PDF/image extraction)",
                    ),
                ),
                (
                    "auto_key_rotation",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically switch to next API key when rate limit is reached",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum retries when all API keys are rate limited",
                    ),
                ),
                (
                    "rate_limit_cooldown_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Minutes to wait before retrying a rate-limited key",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Configuration",
                "verbose_name_plural": "AI Configuration",
            },
        ),
        migrations.CreateModel(
            name="GeminiAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this API key (e.g., 'Production Key 1')",
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Google Gemini API key", max_length=200, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("rate_limited", "Rate Limited"),
                            ("disabled", "Disabled"),
                            ("invalid", "Invalid"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower number = higher priority. Keys are used in priority order.",
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        default=1500,
                        help_text="Daily request limit for free tier (default: 1500)",
                    ),
                ),
                (
                    "minute_limit",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Per-minute request limit for free tier (default: 15)",
                    ),
                ),
                ("requests_today", models.PositiveIntegerField(default=0)),
                ("requests_this_minute", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rate_limited_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Temporarily disabled until this time",
                        null=True,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gemini API Key",
                "verbose_name_plural": "Gemini API Keys",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKeyUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        help_text="Operation type (e.g., 'document_processing', 'chat')",
                        max_length=100,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="ai_companion.geminiapikey",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_usage_logs",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key Usage Log",
                "verbose_name_plural": "API Key Usage Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["api_key", "created_at"],
                        name="ai_companio_api_key_c8564b_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="ai_companio_success_da8e32_idx",
                    ),
                    models.Index(
                        fields=["operation", "created_at"],
                        name="ai_companio_operati_0aa1a8_idx",
                    ),
                ],
            },
        ),
    ]
