# Generated by Django 4.2.13 on 2025-10-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_companion", "0010_add_ai_management_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfiguration",
            name="cache_ttl_minutes",
            field=models.PositiveIntegerField(
                default=60, help_text="How long to cache responses in minutes"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="enable_caching",
            field=models.BooleanField(
                default=True, help_text="Cache AI responses for identical requests"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="enable_content_filtering",
            field=models.BooleanField(
                default=True, help_text="Enable content filtering for AI responses"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="gemini_model",
            field=models.CharField(
                default="gemini-2.0-flash-exp",
                help_text="Gemini model to use (e.g., gemini-2.0-flash-exp, gemini-pro-vision)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="log_all_requests",
            field=models.BooleanField(
                default=True, help_text="Log all AI requests for audit purposes"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="max_tokens",
            field=models.PositiveIntegerField(
                default=2048, help_text="Maximum tokens in AI response"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                help_text="Email to notify about AI system issues",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="notify_on_key_exhaustion",
            field=models.BooleanField(
                default=True,
                help_text="Send notification when all API keys are rate limited",
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="proactive_suggestions_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable or disable proactive AI suggestions"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="request_timeout_seconds",
            field=models.PositiveIntegerField(
                default=30, help_text="Timeout for AI API requests in seconds"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="temperature",
            field=models.FloatField(
                default=0.7,
                help_text="Temperature for AI responses (0.0-1.0). Higher = more creative",
            ),
        ),
    ]
