# Generated by Django 4.2.13 on 2025-11-02 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_companion", "0011_aiconfiguration_cache_ttl_minutes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPendingConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmation_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action_type",
                    models.CharField(
                        help_text="Type of action (e.g., 'approve_po', 'create_so')",
                        max_length=100,
                    ),
                ),
                (
                    "action_params",
                    models.JSONField(
                        default=dict, help_text="Parameters for the action"
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Human-readable summary shown to user"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this confirmation expires"),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_result",
                    models.JSONField(
                        blank=True, default=dict, help_text="Result after execution"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_pending_confirmations",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_pending_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Confirmation",
                "verbose_name_plural": "Pending Confirmations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["confirmation_token"],
                        name="ai_companio_confirm_0ca8fc_idx",
                    ),
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="ai_companio_user_id_f64f15_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "status"],
                        name="ai_companio_expires_488a34_idx",
                    ),
                ],
            },
        ),
    ]
