# Generated by Django 4.2.7 on 2025-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_grni_account",
            field=models.BooleanField(default=False),
        ),
    ]
