# Generated by Django 4.2.7 on 2025-10-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_external_db_connection"),
        ("finance", "0002_account_is_grni_account"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journalvoucher",
            unique_together={("company", "voucher_number")},
        ),
        migrations.AddField(
            model_name="journalvoucher",
            name="sequence_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="journalvoucher",
            unique_together={
                ("company", "voucher_number"),
                ("company", "journal", "sequence_number"),
            },
        ),
        migrations.CreateModel(
            name="JournalSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.CharField(max_length=4)),
                ("current_value", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.journal",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company", "journal", "fiscal_year"],
                        name="finance_jou_company_d25d49_idx",
                    )
                ],
                "unique_together": {("company", "journal", "fiscal_year")},
            },
        ),
    ]
