# Generated by Django 4.2.7 on 2025-10-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("finance", "0003_alter_journalvoucher_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journal",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journalvoucher",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="company_group",
            field=models.ForeignKey(
                default=1,
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
            preserve_default=False,
        ),
    ]
