# Generated by Django 4.2.7 on 2025-10-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("finance", "0004_account_company_group_invoice_company_group_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="journalvoucher",
            unique_together={("company", "voucher_number")},
        ),
    ]
