# Generated by Django 4.2 on 2025-11-04
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_branch_department_departmentmembership_and_more"),
        ("finance", "0005_alter_journalvoucher_unique_together"),
    ]

    operations = [
        # JournalVoucher approvals fields
        migrations.AddField(
            model_name="journalvoucher",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalvoucher",
            name="reviewed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),

        # Invoice approvals
        migrations.AddField(
            model_name="invoice",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),

        # Payment approvals
        migrations.AddField(
            model_name="payment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),

        # Period control
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period", models.CharField(help_text="YYYY-MM", max_length=7)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("CLOSED", "Closed"), ("LOCKED", "Locked")], default="OPEN", max_length=10)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="companies.companygroup")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="companies.company")),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["company", "period", "status"], name="finance_fis_company_c6c6b2_idx")],
                "unique_together": {("company", "period")},
            },
        ),

        # Taxes
        migrations.CreateModel(
            name="TaxJurisdiction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("company_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="companies.companygroup")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="companies.company")),
            ],
            options={
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="TaxCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("is_inclusive", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("company_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="companies.companygroup")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="companies.company")),
                ("input_tax_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to="finance.account")),
                ("output_tax_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to="finance.account")),
                ("jurisdiction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="finance.taxjurisdiction")),
            ],
            options={
                "unique_together": {("company", "code")},
            },
        ),

        # Bank reconciliation
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("statement_date", models.DateField()),
                ("opening_balance", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("closing_balance", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("status", models.CharField(choices=[("IMPORTED", "Imported"), ("PARTIAL", "Partially Matched"), ("RECONCILED", "Reconciled")], default="IMPORTED", max_length=20)),
                ("imported_filename", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="finance.account")),
                ("company_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="companies.companygroup")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="companies.company")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["company", "bank_account", "statement_date"], name="finance_ban_company_10c484_idx")],
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("balance", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("match_status", models.CharField(choices=[("UNMATCHED", "Unmatched"), ("SUGGESTED", "Suggested"), ("MATCHED", "Matched")], default="UNMATCHED", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("matched_payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="finance.payment")),
                ("matched_voucher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="finance.journalvoucher")),
                ("statement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="finance.bankstatement")),
            ],
        ),
    ]

