# Generated by Django 4.2.13 on 2025-11-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_finance_enhancements"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bankstatement",
            new_name="finance_ban_company_307ba9_idx",
            old_name="finance_ban_company_10c484_idx",
        ),
        migrations.RenameIndex(
            model_name="fiscalperiod",
            new_name="finance_fis_company_2c88af_idx",
            old_name="finance_fis_company_c6c6b2_idx",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("POSTED", "Posted"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Fully Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="journalvoucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REVIEW", "In Review"),
                    ("POSTED", "Posted"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("POSTED", "Posted"),
                    ("RECONCILED", "Reconciled"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
