# Generated by Django 4.2.13 on 2025-11-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_inventory_posting_rule"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inventorypostingrule",
            new_name="finance_inv_company_94333e_idx",
            old_name="fin_invpost_wh_txn_idx",
        ),
        migrations.RenameIndex(
            model_name="inventorypostingrule",
            new_name="finance_inv_company_c25cbb_idx",
            old_name="fin_invpost_cat_idx",
        ),
    ]
