# Generated by Django 4.2.13 on 2025-11-05 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_company_default_data_loaded_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "finance",
            "0009_rename_fin_invpost_wh_txn_idx_finance_inv_company_94333e_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code (USD, EUR, BDT, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Currency name (US Dollar, Euro, etc.)", max_length=50
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol ($, €, ৳, etc.)", max_length=10
                    ),
                ),
                (
                    "is_base_currency",
                    models.BooleanField(
                        default=False,
                        help_text="Base currency for this company (only one should be True)",
                    ),
                ),
                (
                    "decimal_places",
                    models.IntegerField(
                        default=2,
                        help_text="Number of decimal places for this currency",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "db_table": "finance_currency",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="currency_balances",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Balances by currency: {'USD': 1000.00, 'EUR': 500.00, 'BDT': 5000.00}",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_default_template",
            field=models.BooleanField(
                default=False,
                help_text="System default account from industry template (can be customized)",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_multi_currency",
            field=models.BooleanField(
                default=False,
                help_text="If True, this account can have transactions in multiple currencies",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                default="BDT",
                help_text="Primary currency for this account (ISO 4217 code)",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Exchange rate: 1 from_currency = rate × to_currency",
                        max_digits=20,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date from which this rate is effective",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("SPOT", "Spot Rate"),
                            ("AVERAGE", "Average Rate"),
                            ("FIXED", "Fixed Rate"),
                            ("BUDGET", "Budget Rate"),
                        ],
                        default="SPOT",
                        help_text="Type of exchange rate",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        help_text="Source currency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates_from",
                        to="finance.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        help_text="Target currency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates_to",
                        to="finance.currency",
                    ),
                ),
            ],
            options={
                "db_table": "finance_exchange_rate",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=[
                            "company",
                            "from_currency",
                            "to_currency",
                            "-effective_date",
                        ],
                        name="finance_exc_company_c67c14_idx",
                    ),
                    models.Index(
                        fields=["company", "effective_date"],
                        name="finance_exc_company_972b6b_idx",
                    ),
                    models.Index(
                        fields=["company", "is_active"],
                        name="finance_exc_company_3927f4_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "company",
                        "from_currency",
                        "to_currency",
                        "effective_date",
                        "rate_type",
                    )
                },
            },
        ),
        migrations.AddIndex(
            model_name="currency",
            index=models.Index(
                fields=["company", "is_active"], name="finance_cur_company_d33009_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="currency",
            index=models.Index(
                fields=["company", "is_base_currency"],
                name="finance_cur_company_d88bd4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="currency",
            unique_together={("company", "code")},
        ),
    ]
