# Generated by Django 4.2.13 on 2025-11-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10004_fix_deliveryorderline_to_sales_product"),
        ("finance", "0010_currency_account_currency_balances_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorypostingrule",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Item category for this posting rule",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_posting_rules",
                to="inventory.itemcategory",
            ),
        ),
    ]
