# Generated by Django 4.2.13 on 2025-11-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10007_warehousebin_movementevent_itemwarehouseconfig_and_more"),
        ("finance", "0011_alter_inventorypostingrule_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorypostingrule",
            name="priority",
            field=models.PositiveIntegerField(
                default=100, help_text="Lower numbers win when multiple rules match"
            ),
        ),
        migrations.AddField(
            model_name="inventorypostingrule",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Item sub-category for this posting rule",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_posting_rules_sub",
                to="inventory.itemcategory",
            ),
        ),
        migrations.AddField(
            model_name="inventorypostingrule",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific warehouse for this rule",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_posting_rules",
                to="inventory.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="inventorypostingrule",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RECEIPT", "Stock Receipt"),
                    ("ISSUE", "Stock Issue"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("SCRAP", "Scrap"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="inventorypostingrule",
            index=models.Index(
                fields=["company", "warehouse"], name="finance_inv_company_58d9d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorypostingrule",
            index=models.Index(
                fields=["company", "priority"], name="finance_inv_company_0b5c93_idx"
            ),
        ),
    ]
