# Generated by Django 4.2.13 on 2025-11-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("budgeting", "0028_line_workflow_backfill"),
        ("finance", "0012_inventorypostingrule_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="projects.project",
            ),
        ),
    ]
