# Generated by Django 4.2.13 on 2025-11-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_inventorypostingrule_item_links"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventorypostingrule",
            index=models.Index(
                fields=["company", "budget_item"], name="finance_inv_company_344372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorypostingrule",
            index=models.Index(
                fields=["company", "item"], name="finance_inv_company_6f77f7_idx"
            ),
        ),
    ]
