# Generated by Django 4.2.7 on 2025-10-27 00:00

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0003_companygroup_remove_company_external_db_connection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "cost_center_type",
                    models.CharField(
                        choices=[
                            ("department", "Department"),
                            ("branch", "Branch"),
                            ("program", "Program / Grant"),
                            ("project", "Project"),
                            ("production_line", "Production Line"),
                        ],
                        default="department",
                        max_length=32,
                    ),
                ),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("kpi_snapshot", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_centers",
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_centers",
                        to="companies.companygroup",
                    ),
                ),
                (
                    "deputy_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_cost_centers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_cost_centers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="budgeting.costcenter",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("company", "code")},
                "indexes": [
                    models.Index(fields=["company", "cost_center_type"], name="budgeting_c_company_b28430_idx"),
                    models.Index(fields=["company", "is_active"], name="budgeting_c_company_964e12_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="Untitled Budget", max_length=255, null=True)),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("operational", "Operational / Production"),
                            ("opex", "Department OPEX"),
                            ("capex", "Capital Expenditure"),
                            ("revenue", "Revenue Target"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ("period_end", models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "consumed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("threshold_percent", models.PositiveIntegerField(default=90)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROPOSED", "Proposed"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ACTIVE", "Active"),
                            ("LOCKED", "Locked"),
                            ("CLOSED", "Closed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("workflow_state", models.CharField(blank=True, default="", max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="companies.company",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "-created_at"],
                "indexes": [
                    models.Index(fields=["company", "budget_type", "status"], name="budgeting_b_company_a6095c_idx"),
                    models.Index(fields=["period_start", "period_end"], name="budgeting_b_period__d9335e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["cost_center", "budget_type", "period_start", "period_end"],
                        name="unique_budget_period_per_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "procurement_class",
                    models.CharField(
                        choices=[
                            ("stock_item", "Stock Item"),
                            ("service_item", "Service / Expense"),
                            ("capex_item", "Capex Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_code", models.CharField(blank=True, max_length=64)),
                ("item_name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("project_code", models.CharField(blank=True, max_length=64)),
                ("qty_limit", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=15)),
                ("value_limit", models.DecimalField(decimal_places=2, max_digits=20)),
                ("standard_price", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20)),
                ("tolerance_percent", models.PositiveIntegerField(default=5)),
                ("consumed_quantity", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=15)),
                ("consumed_value", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="budgeting.budget",
                    ),
                ),
                (
                    "budget_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_budget_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
                "indexes": [
                    models.Index(fields=["budget", "procurement_class"], name="budgeting_b_budget__8d9b4c_idx"),
                    models.Index(fields=["item_code"], name="budgeting_b_item_co_a819b1_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=["budget", "sequence"], name="unique_budget_line_sequence"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetConsumptionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(default=django.utils.timezone.now)),
                ("total_limit", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_consumed", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_remaining", models.DecimalField(decimal_places=2, max_digits=20)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="budgeting.budget",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "constraints": [
                    models.UniqueConstraint(fields=["budget", "snapshot_date"], name="unique_budget_snapshot_per_day"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetOverrideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("requested_quantity", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=15)),
                ("requested_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("decision_notes", models.TextField(blank=True)),
                ("reference_type", models.CharField(blank=True, max_length=64)),
                ("reference_id", models.CharField(blank=True, max_length=64)),
                ("severity", models.CharField(blank=True, default="", max_length=32)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_override_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="override_requests",
                        to="budgeting.budgetline",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_override_requests",
                        to="companies.company",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="override_requests",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_override_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["company", "status"], name="budgeting_b_company_384006_idx"),
                    models.Index(fields=["reference_type", "reference_id"], name="budgeting_b_referen_f62276_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("stock_issue", "Stock Issue"),
                            ("service_receipt", "Service Delivery"),
                            ("capex_receipt", "Capex Receipt"),
                            ("journal", "Finance Journal"),
                            ("manual_adjust", "Manual Adjustment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("reference_type", models.CharField(max_length=64)),
                ("reference_id", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="budgeting.budgetline",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["reference_type", "reference_id"], name="budgeting_b_referen_0454ab_idx"),
                ],
            },
        ),
    ]
