# Generated by Django 4.2.7 on 2025-10-29 15:32

from django.db import migrations, models
from django.db.models import F
from django.db.utils import ProgrammingError
from django.utils import timezone


def hydrate_budget_defaults(apps, schema_editor):
    Budget = apps.get_model("budgeting", "Budget")
    today = timezone.now().date()
    table_name = Budget._meta.db_table

    connection = schema_editor.connection
    try:
        with connection.cursor() as cursor:
            columns = {col.name for col in connection.introspection.get_table_description(cursor, table_name)}
    except ProgrammingError:
        return

    required_columns = {"name", "period_start", "period_end"}
    if not required_columns.issubset(columns):
        return

    Budget.objects.filter(name__isnull=True).update(name="Untitled Budget")
    Budget.objects.filter(name="").update(name="Untitled Budget")

    Budget.objects.filter(period_start__isnull=True).update(period_start=today)
    Budget.objects.filter(period_end__isnull=True, period_start__isnull=False).update(period_end=F("period_start"))
    Budget.objects.filter(period_end__isnull=True, period_start__isnull=True).update(
        period_start=today, period_end=today
    )


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE budgeting_budget ADD COLUMN IF NOT EXISTS name varchar(255);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE budgeting_budget ADD COLUMN IF NOT EXISTS period_start date;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE budgeting_budget ADD COLUMN IF NOT EXISTS period_end date;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(hydrate_budget_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.CharField(default="Untitled Budget", max_length=255),
        ),
        migrations.AlterField(
            model_name="budget",
            name="period_end",
            field=models.DateField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name="budget",
            name="period_start",
            field=models.DateField(default=timezone.now),
        ),
    ]
