# Generated by Django 4.2.7 on 2025-10-29 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgeting", "0002_auto_20251029_2132"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_company_type_status_idx RENAME TO budgeting_b_company_a6095c_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_b_company_a6095c_idx RENAME TO budget_company_type_status_idx;",
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_period_idx RENAME TO budgeting_b_period__d9335e_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_b_period__d9335e_idx RENAME TO budget_period_idx;",
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_line_class_idx RENAME TO budgeting_b_budget__8d9b4c_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_b_budget__8d9b4c_idx RENAME TO budget_line_class_idx;",
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_line_item_code_idx RENAME TO budgeting_b_item_co_a819b1_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_b_item_co_a819b1_idx RENAME TO budget_line_item_code_idx;",
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_override_status_idx RENAME TO budgeting_b_company_384006_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_b_company_384006_idx RENAME TO budget_override_status_idx;",
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_override_reference_idx RENAME TO budgeting_b_referen_f62276_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_b_referen_f62276_idx RENAME TO budget_override_reference_idx;",
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_usage_reference_idx RENAME TO budgeting_b_referen_0454ab_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_b_referen_0454ab_idx RENAME TO budget_usage_reference_idx;",
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_cc_type_idx RENAME TO budgeting_c_company_b28430_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_c_company_b28430_idx RENAME TO budget_cc_type_idx;",
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS budget_cc_active_idx RENAME TO budgeting_c_company_964e12_idx;",
            reverse_sql="ALTER INDEX IF EXISTS budgeting_c_company_964e12_idx RENAME TO budget_cc_active_idx;",
        ),
        migrations.AlterField(
            model_name="budgetoverriderequest",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_override_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="name",
            field=models.CharField(
                blank=True, default="Untitled Budget", max_length=255, null=True
            ),
        ),
    ]
