# Generated by Django 4.2.7 on 2025-10-29 17:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
        (
            "budgeting",
            "0003_rename_budget_company_type_status_idx_budgeting_b_company_a6095c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetline",
            name="committed_quantity",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="committed_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="budgetusage",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("stock_issue", "Stock Issue"),
                    ("service_receipt", "Service Delivery"),
                    ("capex_receipt", "Capex Receipt"),
                    ("journal", "Finance Journal"),
                    ("manual_adjust", "Manual Adjustment"),
                    ("procurement_receipt", "Procurement Receipt"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="BudgetCommitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("converted", "Converted to Order"),
                            ("released", "Released"),
                            ("consumed", "Consumed"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("source_type", models.CharField(max_length=32)),
                ("source_reference", models.CharField(max_length=64)),
                (
                    "committed_quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "committed_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "consumed_quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "consumed_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "released_quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "released_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="budgeting.budgetline",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_commitments",
                        to="companies.company",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_commitments",
                        to="budgeting.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budget_commitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="budgeting_b_company_a8bc21_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_reference"],
                        name="budgeting_b_source__481491_idx",
                    ),
                ],
                "unique_together": {("budget_line", "source_type", "source_reference")},
            },
        ),
    ]
