# Generated by Django 4.2.7 on 2025-10-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0004_budgetline_committed_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetusage",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("stock_issue", "Stock Issue"),
                    ("service_receipt", "Service Delivery"),
                    ("capex_receipt", "Capex Receipt"),
                    ("journal", "Finance Journal"),
                    ("manual_adjust", "Manual Adjustment"),
                    ("procurement_receipt", "Procurement Receipt"),
                    ("overtime", "Overtime"),
                ],
                max_length=40,
            ),
        ),
    ]
