# Generated by Django 4.2.7 on 2025-10-31 07:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0006_budgetitemcode"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="budgetitemcode",
            new_name="budgeting_b_company_fc7191_idx",
            old_name="budgeting_b_company_code_idx",
        ),
        migrations.RenameIndex(
            model_name="budgetitemcode",
            new_name="budgeting_b_company_3fec6e_idx",
            old_name="budgeting_b_company_active_idx",
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="standard_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=20
            ),
        ),
    ]
