# Generated by Django 4.2.13 on 2025-11-03 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgeting", "0010_budget_company_wide"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="budgetapproval",
            new_name="budgeting_b_budget__1ca015_idx",
            old_name="budget_appr_budget_ap_3b31b3_idx",
        ),
        migrations.RenameIndex(
            model_name="budgetapproval",
            new_name="budgeting_b_approve_93193d_idx",
            old_name="budget_appr_approver__b4307b_idx",
        ),
        migrations.AddField(
            model_name="costcenter",
            name="budget_entry_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can enter budget lines for this cost center",
                related_name="budget_entry_cost_centers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ENTRY_OPEN", "Entry Open"),
                    ("PENDING_CC_APPROVAL", "Pending CC Approval"),
                    ("CC_APPROVED", "CC Approved"),
                    ("PENDING_FINAL_APPROVAL", "Pending Final Approval"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("CLOSED", "Closed"),
                ],
                default="DRAFT",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="budgetapproval",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
