# Generated by Django 4.2.13 on 2025-11-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0011_budget_amount_default_zero"),
        (
            "budgeting",
            "0011_rename_budget_appr_budget_ap_3b31b3_idx_budgeting_b_budget__1ca015_idx_and_more",
        ),
    ]

    operations = []
