# Generated by Django 4.2.13 on 2025-11-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_branch_department_departmentmembership_and_more"),
        ("budgeting", "0014_alter_budget_amount_alter_budgetpricepolicy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="costcenter",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch (optional, derived from department if not set)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_centers",
                to="companies.branch",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department this cost center belongs to (required for new records)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_centers",
                to="companies.department",
            ),
        ),
        migrations.AddIndex(
            model_name="costcenter",
            index=models.Index(
                fields=["department", "is_active"],
                name="budgeting_c_departm_d498c1_idx",
            ),
        ),
    ]
