# Generated by Django 4.2.13 on 2025-11-04 16:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0005_branch_department_departmentmembership_and_more"),
        ("budgeting", "0015_costcenter_branch_costcenter_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetRemarkTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "Qty Exceeds Standard"', max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "template_text",
                    models.TextField(
                        help_text="Remark text (can include placeholders like {item_name}, {qty})"
                    ),
                ),
                (
                    "remark_type",
                    models.CharField(
                        choices=[
                            ("suggestion", "Suggestion"),
                            ("concern", "Concern"),
                            ("approval_note", "Approval Note"),
                            ("clarification_needed", "Clarification Needed"),
                            ("data_issue", "Data Issue"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "is_predefined",
                    models.BooleanField(
                        default=False,
                        help_text="True if predefined by system; False if custom",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="How many times used"),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=True, help_text="Visible to all moderators if True"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "budget_remark_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetVarianceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("qty_change", "Quantity Changed"),
                            ("price_change", "Price Changed"),
                            ("both_change", "Qty & Price Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_qty", models.DecimalField(decimal_places=3, max_digits=15)),
                ("new_qty", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "qty_change_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "price_change_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "original_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("new_value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "value_variance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, help_text="Why this change was made"),
                ),
                (
                    "role_of_modifier",
                    models.CharField(
                        choices=[
                            ("cc_owner", "CC Owner"),
                            ("moderator", "Moderator"),
                            ("module_owner", "Module Owner"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "budget_variance_audit",
                "ordering": ["-modified_at"],
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="activated_at",
            field=models.DateTimeField(
                blank=True, help_text="When budget was activated", null=True
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="activated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who activated budget (turned on impact tracking)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="auto_approve_by_role",
            field=models.CharField(
                blank=True,
                default="Module Owner (System)",
                help_text="Which role should be recorded as auto-approver",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="auto_approve_if_not_approved",
            field=models.BooleanField(
                default=False,
                help_text="Auto-approve budget at budget start date if not approved yet",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="auto_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When budget was auto-approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_impact_enabled",
            field=models.BooleanField(
                default=False, help_text="Toggle to enable/disable consumption tracking"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_impact_end_date",
            field=models.DateField(
                blank=True, help_text="When consumption tracking stops", null=True
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_impact_start_date",
            field=models.DateField(
                blank=True, help_text="When consumption tracking begins", null=True
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="committed",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total committed amount",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="custom_duration_days",
            field=models.IntegerField(
                blank=True, help_text="Days if duration_type=custom", null=True
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="duration_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("half_yearly", "Half Yearly"),
                    ("yearly", "Yearly"),
                    ("custom", "Custom"),
                ],
                default="yearly",
                help_text="Budget duration type",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="entry_enabled",
            field=models.BooleanField(
                default=True, help_text="Toggle to enable/disable entry period"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="final_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When budget was finally approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="final_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Module owner who gave final approval",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="final_approved_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="grace_period_days",
            field=models.IntegerField(
                default=3, help_text="Days after entry period ends before review starts"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="moderator_reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When moderator completed review", null=True
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="moderator_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator who reviewed this budget",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderator_reviewed_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="remaining",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total remaining amount",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="review_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Auto-enabled when first item sent back for review",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="review_end_date",
            field=models.DateField(
                blank=True, help_text="When review period ends", null=True
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="review_start_date",
            field=models.DateField(
                blank=True,
                help_text="When review period starts (auto-calculated from entry_end + grace)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="total_variance_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of all line modifications (original vs modified)",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="total_variance_count",
            field=models.IntegerField(
                default=0, help_text="Number of lines with modifications"
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="cc_owner_modification_notes",
            field=models.TextField(
                blank=True, help_text="CC Owner notes for modifications"
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="held_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked this line as held",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_budget_lines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="held_reason",
            field=models.TextField(
                blank=True, help_text="Reason for holding this line"
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="held_until_date",
            field=models.DateTimeField(
                blank=True, help_text="Hold expires on this date", null=True
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="is_held_for_review",
            field=models.BooleanField(
                default=False,
                help_text="Marked as held for further review by owner/moderator",
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="moderator_remarks",
            field=models.TextField(
                blank=True, help_text="Moderator comments on this line"
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="moderator_remarks_at",
            field=models.DateTimeField(
                blank=True, help_text="When moderator added remarks", null=True
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="moderator_remarks_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator who added remarks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_line_remarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="modification_reason",
            field=models.TextField(
                blank=True, help_text="Justification for modification"
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="modified_at",
            field=models.DateTimeField(
                blank=True, help_text="When line was last modified", null=True
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this line",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_budget_lines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="original_qty_limit",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Original quantity at submission",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="original_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Original price at submission",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="original_value_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Original value at submission",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="price_variance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Current Price - Original Price",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="projected_consumption_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Confidence level (0-100) for projection",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="projected_consumption_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="AI-predicted consumption based on trends",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="qty_variance",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Current Qty - Original Qty",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="sent_back_for_review",
            field=models.BooleanField(
                default=False, help_text="Sent back to CC owner/entry user for review"
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="value_variance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Current Value - Original Value",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="variance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="% change from original",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="will_exceed_budget",
            field=models.BooleanField(
                default=False, help_text="True if projected consumption > allocated"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total allocated budget amount",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="consumed",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total consumed amount",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="entry_end_date",
            field=models.DateField(
                blank=True,
                help_text="Deadline for department users to submit budget",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="entry_start_date",
            field=models.DateField(
                blank=True,
                help_text="When department users can start entering budget lines",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="period_end",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="When budget expires"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="period_start",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="When budget becomes effective",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ENTRY_OPEN", "Entry Open"),
                    ("ENTRY_CLOSED_REVIEW_PENDING", "Entry Closed - Review Pending"),
                    ("REVIEW_OPEN", "Review Period Open"),
                    ("PENDING_CC_APPROVAL", "Pending CC Approval"),
                    ("CC_APPROVED", "CC Approved"),
                    ("PENDING_MODERATOR_REVIEW", "Pending Moderator Review"),
                    ("MODERATOR_REVIEWED", "Moderator Reviewed"),
                    ("PENDING_FINAL_APPROVAL", "Pending Final Approval"),
                    ("APPROVED", "Approved"),
                    ("AUTO_APPROVED", "Auto Approved"),
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("CLOSED", "Closed"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="budgetline",
            name="value_limit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AddIndex(
            model_name="budgetline",
            index=models.Index(
                fields=["budget", "is_active"], name="budgeting_b_budget__833a63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetline",
            index=models.Index(
                fields=["is_held_for_review"], name="budgeting_b_is_held_834ce9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetline",
            index=models.Index(
                fields=["sent_back_for_review"], name="budgeting_b_sent_ba_d4ca82_idx"
            ),
        ),
        migrations.AddField(
            model_name="budgetvarianceaudit",
            name="budget_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variance_audit_trail",
                to="budgeting.budgetline",
            ),
        ),
        migrations.AddField(
            model_name="budgetvarianceaudit",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetremarktemplate",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_remark_templates",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="budgetremarktemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_budget_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="budgetvarianceaudit",
            index=models.Index(
                fields=["budget_line"], name="budget_vari_budget__c97d7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetvarianceaudit",
            index=models.Index(
                fields=["modified_at"], name="budget_vari_modifie_29b79f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetvarianceaudit",
            index=models.Index(
                fields=["modified_by"], name="budget_vari_modifie_303c68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetremarktemplate",
            index=models.Index(
                fields=["company", "is_predefined"],
                name="budget_rema_company_ddd8bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetremarktemplate",
            index=models.Index(
                fields=["company", "is_shared"], name="budget_rema_company_bd0894_idx"
            ),
        ),
    ]
