# Generated by Django 4.2.13 on 2025-11-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10001_item_itemcategory_alter_productcategory_options_and_more"),
        ("sales", "0005_taxcategory_productcategory_product_and_more"),
        ("budgeting", "0016_budgetremarktemplate_budgetvarianceaudit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                help_text="For expense/capex/operational budgets - inventory item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_lines",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Sub-category for budget classification",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_lines",
                to="inventory.itemcategory",
            ),
        ),
        migrations.AlterField(
            model_name="budgetline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="For revenue budgets only - saleable product",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_lines",
                to="sales.product",
            ),
        ),
    ]
