# Generated by Django 4.2.13 on 2025-11-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("inventory", "10005_uom_add_group_unique"),
        ("budgeting", "0020_item_categories_group_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetUnitOfMeasure",
            fields=[],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.unitofmeasure",),
        ),
        migrations.RemoveConstraint(
            model_name="budgetitemcode",
            name="itemcode_unique_per_group_code",
        ),
        migrations.AlterField(
            model_name="budgetitemcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="companies.companygroup",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemsubcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitemcategory",
            index=models.Index(
                fields=["company", "code"], name="budgeting_b_company_3e5ecf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitemcategory",
            index=models.Index(
                fields=["company", "is_active"], name="budgeting_b_company_71e29d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitemsubcategory",
            index=models.Index(
                fields=["company", "category"], name="budgeting_b_company_9e692e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitemsubcategory",
            index=models.Index(
                fields=["category", "code"], name="budgeting_b_categor_58a33a_idx"
            ),
        ),
    ]
