# Generated by Django 4.2.13 on 2025-11-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("budgeting", "0021_budgetunitofmeasure_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="budgetitemcategory",
            name="budgeting_b_company_71e29d_idx",
        ),
        migrations.RemoveIndex(
            model_name="budgetitemcode",
            name="budgeting_b_company_fc7191_idx",
        ),
        migrations.RemoveIndex(
            model_name="budgetitemcode",
            name="budgeting_b_company_3fec6e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="budgetitemcode",
            unique_together={("company_group", "code")},
        ),
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ENTRY_OPEN", "Entry Open"),
                    ("ENTRY_CLOSED_REVIEW_PENDING", "Entry Closed - Review Pending"),
                    ("REVIEW_OPEN", "Review Period Open"),
                    ("PENDING_CC_APPROVAL", "Pending CC Approval"),
                    ("CC_APPROVED", "CC Approved"),
                    ("PENDING_MODERATOR_REVIEW", "Pending Moderator Review"),
                    ("MODERATOR_REVIEWED", "Moderator Reviewed"),
                    ("PENDING_FINAL_APPROVAL", "Pending Final Approval"),
                    ("APPROVED", "Approved"),
                    ("AUTO_APPROVED", "Auto Approved"),
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("CLOSED", "Closed"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="budgetapproval",
            name="approver_type",
            field=models.CharField(
                choices=[
                    ("budget_name_approver", "Budget Name Approver"),
                    ("cost_center_owner", "Cost Center Owner"),
                    ("budget_module_owner", "Budget Module Owner"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcategory",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_item_categories",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_item_codes",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemsubcategory",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_item_subcategories",
                to="companies.company",
            ),
        ),
        migrations.RemoveField(
            model_name="budgetitemcode",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="budgetitemcode",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="budgetitemcode",
            name="standard_price",
        ),
        migrations.RemoveField(
            model_name="budgetitemcode",
            name="uom",
        ),
        migrations.RemoveField(
            model_name="budgetitemcode",
            name="updated_at",
        ),
    ]
