# Generated by Django 4.2.13 on 2025-11-08 10:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10006_alter_unitofmeasure_options_and_more"),
        (
            "budgeting",
            "0022_remove_budgetitemcategory_budgeting_b_company_71e29d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetitemcode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="standard_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="uom",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_item_codes",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
