# Generated by Django 4.2.13 on 2025-11-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10006_alter_unitofmeasure_options_and_more"),
        ("budgeting", "0025_budget_name_status_and_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="auto_activate",
            field=models.BooleanField(
                default=False,
                help_text="If ON, auto-activate on period start (excludes held lines)",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="uom",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_item_codes",
                to="inventory.unitofmeasure",
            ),
            preserve_default=False,
        ),
    ]
