# Generated by Django 4.2.13 on 2025-11-10 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgeting", "0026_alter_budget_auto_activate_alter_budgetitemcode_uom"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetline",
            name="cc_decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("SENT_BACK", "Sent Back"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="cc_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="cc_decision_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made CC decision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cc_decided_budget_lines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="final_decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="final_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="final_decision_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made final decision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="final_decided_budget_lines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="moderator_state",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("REMARKED", "Remarked"),
                    ("HELD", "Held"),
                    ("SENT_BACK", "Sent Back"),
                ],
                default="NONE",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="BudgetApprovalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("CC_APPROVAL", "Cost Center Approval"),
                            ("FINAL_APPROVAL", "Final Approval"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SENT_BACK", "Sent Back"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_lines",
                        to="budgeting.budgetapproval",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_scopes",
                        to="budgeting.budgetline",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["approval", "stage", "status"], name="bal_appr_sts"
                    ),
                    models.Index(
                        fields=["line", "stage", "status"], name="bal_line_sts"
                    ),
                ],
                "unique_together": {("approval", "line")},
            },
        ),
    ]
