# Generated by Django 4.2.13 on 2025-11-11 17:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0015_inventorypostingrule_finance_inv_company_344372_idx_and_more",
        ),
        ("inventory", "10025_materialissue_materialissueline_and_more"),
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budgeting", "0029_budget_item_inventory_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetItemFinanceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_category",
                    models.CharField(
                        blank=True, help_text="Tax category code", max_length=50
                    ),
                ),
                (
                    "is_tax_exempt",
                    models.BooleanField(default=False, help_text="Exempt from taxes"),
                ),
                (
                    "require_budget_check",
                    models.BooleanField(
                        default=True,
                        help_text="Require budget availability before transactions",
                    ),
                ),
                (
                    "allow_over_budget",
                    models.BooleanField(
                        default=False, help_text="Allow transactions exceeding budget"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Finance-specific notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item Finance Profile",
                "verbose_name_plural": "Item Finance Profiles",
                "db_table": "budget_item_finance_profile",
            },
        ),
        migrations.CreateModel(
            name="BudgetItemInventoryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "safety_stock_level",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Safety stock to maintain",
                        max_digits=15,
                    ),
                ),
                (
                    "max_stock_level",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Maximum stock level",
                        max_digits=15,
                    ),
                ),
                (
                    "auto_replenish",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically create replenishment requests",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Weight per unit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "weight_uom",
                    models.CharField(
                        blank=True,
                        help_text="Weight unit (kg, lbs, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Volume per unit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume_uom",
                    models.CharField(
                        blank=True, help_text="Volume unit (m3, L, etc.)", max_length=10
                    ),
                ),
                (
                    "shelf_life_days",
                    models.IntegerField(
                        default=0, help_text="Shelf life in days (0=no expiry)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Inventory-specific notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Item Inventory Profile",
                "verbose_name_plural": "Item Inventory Profiles",
                "db_table": "budget_item_inventory_profile",
            },
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current cost price",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_budget_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_items",
                to="companies.department",
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="description",
            field=models.TextField(blank=True, help_text="Detailed item description"),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="expiry_warning_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Days before expiry to warn (0=disabled)"
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="is_tradable",
            field=models.BooleanField(
                default=False, help_text="Can be linked to saleable products"
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="lead_time_days",
            field=models.IntegerField(
                default=0, help_text="Procurement lead time in days"
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="prevent_expired_issuance",
            field=models.BooleanField(
                default=True, help_text="Prevent issuing expired stock"
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="reorder_level",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Minimum stock level for reorder trigger",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="reorder_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Quantity to reorder",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="standard_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Standard cost for variance calculation",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning"),
                    ("ACTIVE", "Active"),
                    ("OBSOLETE", "Obsolete"),
                ],
                default="PLANNING",
                help_text="PLANNING: budgeting only; ACTIVE: inventory operations enabled; OBSOLETE: historical only",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="track_inventory",
            field=models.BooleanField(
                default=True, help_text="Whether to track stock levels"
            ),
        ),
        migrations.AddField(
            model_name="budgetitemcode",
            name="valuation_method",
            field=models.CharField(
                choices=[
                    ("FIFO", "First In, First Out"),
                    ("LIFO", "Last In, First Out"),
                    ("WEIGHTED_AVG", "Weighted Average"),
                    ("STANDARD_COST", "Standard Cost"),
                ],
                default="FIFO",
                help_text="Inventory valuation method",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for issues",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_item_expense_accounts",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Inventory asset account",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_item_inventory_accounts",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Active flag (legacy, prefer status field)"
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="is_batch_tracked",
            field=models.BooleanField(
                default=False, help_text="Track by batch/lot number"
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="is_serial_tracked",
            field=models.BooleanField(
                default=False, help_text="Track by serial number"
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="requires_fefo",
            field=models.BooleanField(
                default=False, help_text="First Expire, First Out required"
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="standard_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Standard/list price",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="stock_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="UOM for stock tracking",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="uom",
            field=models.ForeignKey(
                help_text="Base unit of measure",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_item_codes",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitemcode",
            name="valuation_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Current valuation rate for Material Issue",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitemcode",
            index=models.Index(
                fields=["company", "status"], name="budgeting_b_company_c0a0e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitemcode",
            index=models.Index(
                fields=["company", "item_type", "status"],
                name="budgeting_b_company_10df4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitemcode",
            index=models.Index(
                fields=["status", "is_active"], name="budgeting_b_status_de1dd9_idx"
            ),
        ),
        migrations.AddField(
            model_name="budgetiteminventoryprofile",
            name="budget_item",
            field=models.OneToOneField(
                help_text="Budget item this profile extends",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_profile",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="budgetiteminventoryprofile",
            name="preferred_bin",
            field=models.ForeignKey(
                blank=True,
                help_text="Default bin location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inventory.warehousebin",
            ),
        ),
        migrations.AddField(
            model_name="budgetiteminventoryprofile",
            name="preferred_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Default warehouse for this item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="budgetiteminventoryprofile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetitemfinanceprofile",
            name="accrual_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Accrual account for this item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="budgetitemfinanceprofile",
            name="budget_item",
            field=models.OneToOneField(
                help_text="Budget item this profile extends",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_profile",
                to="budgeting.budgetitemcode",
            ),
        ),
        migrations.AddField(
            model_name="budgetitemfinanceprofile",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cost of Goods Sold account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="budgetitemfinanceprofile",
            name="default_cost_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Default cost center for this item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="budgeting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="budgetitemfinanceprofile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetitemfinanceprofile",
            name="variance_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Price/quantity variance account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.account",
            ),
        ),
    ]
