# Generated by Django 4.2.13 on 2025-11-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0030_unified_item_master"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetline",
            name="item",
        ),
    ]
