# Generated by Django 4.2.7 on 2025-10-23 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("target_module", models.CharField(max_length=50)),
                ("target_model", models.CharField(max_length=50)),
                ("field_mappings", models.JSONField(default=dict)),
                ("validation_rules", models.JSONField(default=dict)),
                ("transformation_rules", models.JSONField(default=dict)),
                ("default_values", models.JSONField(default=dict)),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Available to all users in company"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "name", "target_model")},
            },
        ),
        migrations.CreateModel(
            name="MigrationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.UUIDField(editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("EXCEL", "Excel File"),
                            ("CSV", "CSV File"),
                            ("DATABASE", "Database"),
                            ("API", "API Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True, null=True, upload_to="migrations/%Y/%m/"
                    ),
                ),
                (
                    "source_connection",
                    models.JSONField(
                        blank=True, help_text="Database connection info", null=True
                    ),
                ),
                ("target_module", models.CharField(max_length=50)),
                ("target_model", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "File Uploaded"),
                            ("PROFILED", "Data Profiled"),
                            ("MAPPED", "Fields Mapped"),
                            ("VALIDATED", "Validation Complete"),
                            ("IMPORTING", "Import in Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("success_rows", models.IntegerField(default=0)),
                ("error_rows", models.IntegerField(default=0)),
                ("skipped_rows", models.IntegerField(default=0)),
                ("mapping_config", models.JSONField(default=dict)),
                ("validation_rules", models.JSONField(default=dict)),
                ("transformation_rules", models.JSONField(default=dict)),
                ("save_as_template", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data_migration.migrationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_model", models.CharField(max_length=50)),
                ("target_id", models.IntegerField()),
                ("source_row_number", models.IntegerField()),
                ("source_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="data_migration.migrationsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MigrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("row_number", models.IntegerField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="data_migration.migrationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("source_data", models.JSONField()),
                ("error_type", models.CharField(max_length=50)),
                ("error_message", models.TextField()),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("can_retry", models.BooleanField(default=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="data_migration.migrationsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("columns", models.JSONField(default=list)),
                ("column_types", models.JSONField(default=dict)),
                ("column_stats", models.JSONField(default=dict)),
                ("null_counts", models.JSONField(default=dict)),
                ("unique_counts", models.JSONField(default=dict)),
                ("duplicate_rows", models.IntegerField(default=0)),
                ("sample_rows", models.JSONField(default=list)),
                ("profiled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="data_migration.migrationsession",
                    ),
                ),
            ],
            options={
                "db_table": "migration_data_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="migrationsession",
            index=models.Index(
                fields=["company", "status"], name="data_migrat_company_1ec38d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="migrationsession",
            index=models.Index(
                fields=["company", "target_module"],
                name="data_migrat_company_491832_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="migrationrecord",
            index=models.Index(
                fields=["session", "target_model"],
                name="data_migrat_session_188307_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="migrationlog",
            index=models.Index(
                fields=["session", "log_level"], name="data_migrat_session_da2b09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="migrationerror",
            index=models.Index(
                fields=["session", "is_resolved"], name="data_migrat_session_1af54e_idx"
            ),
        ),
    ]
