# Generated by Django 4.2.7 on 2025-10-27 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("data_migration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "migration_job_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "entity_name_guess",
                    models.CharField(
                        blank=True,
                        help_text="Initial entity guess supplied by uploader or detector",
                        max_length=100,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True,
                        help_text="Django model label (app_label.ModelName) resolved for this job",
                        max_length=150,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("detected", "Structure Detected"),
                            ("mapped", "Field Mapping Prepared"),
                            ("validated", "Validated"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("committing", "Commit In Progress"),
                            ("committed", "Committed"),
                            ("rolled_back", "Rolled Back"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=32,
                    ),
                ),
                (
                    "submitted_for_approval_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_migration_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "committed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committed_migration_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        help_text="Company group this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.companygroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rollback_parent_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_children",
                        to="data_migration.migrationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationStagingRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("row_index_in_file", models.IntegerField()),
                ("clean_payload_json", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_validation", "Pending Validation"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending_validation",
                        max_length=24,
                    ),
                ),
                ("validation_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "migration_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_rows",
                        to="data_migration.migrationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index_in_file"],
            },
        ),
        migrations.AddField(
            model_name="migrationsession",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Company group this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
        ),
        migrations.AddField(
            model_name="migrationtemplate",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Company group this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
        ),
        migrations.CreateModel(
            name="MigrationSchemaExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("proposed_definition", models.JSONField()),
                (
                    "metadata_layer",
                    models.CharField(
                        help_text="Which metadata layer to apply the change to (e.g. COMPANY_OVERRIDE)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metadata_extension_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "migration_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_extensions",
                        to="data_migration.migrationjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MigrationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True, null=True, upload_to="migration_uploads/%Y/%m/%d"
                    ),
                ),
                (
                    "stored_path",
                    models.CharField(
                        blank=True,
                        help_text="Physical storage reference (filesystem path, S3 key, etc.)",
                        max_length=512,
                    ),
                ),
                ("file_hash", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("parsed", "Parsed"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
                ("row_count_detected", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "migration_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="data_migration.migrationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name_in_file", models.CharField(max_length=255)),
                ("target_entity_field", models.CharField(blank=True, max_length=255)),
                (
                    "target_storage_mode",
                    models.CharField(
                        choices=[
                            ("column", "Existing Column"),
                            ("extra_data_new_field", "New Extra Data Field"),
                            ("ignore", "Ignore"),
                        ],
                        default="column",
                        max_length=32,
                    ),
                ),
                ("new_field_definition_json", models.JSONField(blank=True, null=True)),
                ("is_required_match", models.BooleanField(default=False)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_field_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "migration_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="data_migration.migrationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["column_name_in_file"],
            },
        ),
        migrations.CreateModel(
            name="MigrationCommitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "committed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "summary",
                    models.JSONField(
                        default=dict,
                        help_text="Counts, totals, and other diagnostics for the commit.",
                    ),
                ),
                (
                    "created_records",
                    models.JSONField(
                        default=list,
                        help_text="List of dicts describing created record identifiers for rollback.",
                    ),
                ),
                (
                    "gl_entries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Journal vouchers or GL impacts produced during commit.",
                    ),
                ),
                ("extra_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "committed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migration_commit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "migration_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commit_log",
                        to="data_migration.migrationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-committed_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationColumnProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name_in_file", models.CharField(max_length=255)),
                ("detected_data_type", models.CharField(max_length=50)),
                (
                    "inferred_field_name",
                    models.CharField(
                        blank=True,
                        help_text="Best-guess normalized field name (snake_case)",
                        max_length=255,
                    ),
                ),
                ("sample_values", models.JSONField(blank=True, default=list)),
                ("stats", models.JSONField(blank=True, default=dict)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "migration_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_profiles",
                        to="data_migration.migrationfile",
                    ),
                ),
                (
                    "migration_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_profiles",
                        to="data_migration.migrationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["column_name_in_file"],
            },
        ),
        migrations.CreateModel(
            name="MigrationValidationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_code", models.CharField(max_length=100)),
                ("error_message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("hard", "Hard Error"), ("soft", "Soft Warning")],
                        default="hard",
                        max_length=8,
                    ),
                ),
                ("suggested_fix", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_errors",
                        to="data_migration.migrationfieldmapping",
                    ),
                ),
                (
                    "migration_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_errors",
                        to="data_migration.migrationjob",
                    ),
                ),
                (
                    "staging_row",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="data_migration.migrationstagingrow",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["migration_job", "severity"],
                        name="data_migrat_migrati_3c0528_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="migrationstagingrow",
            index=models.Index(
                fields=["migration_job", "status"],
                name="data_migrat_migrati_0bcd89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="migrationschemaextension",
            index=models.Index(
                fields=["migration_job", "status"],
                name="data_migrat_migrati_79bdbc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="migrationschemaextension",
            unique_together={("migration_job", "field_name")},
        ),
        migrations.AddIndex(
            model_name="migrationjob",
            index=models.Index(
                fields=["company", "status"], name="data_migrat_company_49febb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="migrationjob",
            index=models.Index(
                fields=["company", "target_model"],
                name="data_migrat_company_bf91c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="migrationfile",
            index=models.Index(
                fields=["migration_job", "status"],
                name="data_migrat_migrati_6052c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="migrationfile",
            index=models.Index(
                fields=["file_hash"], name="data_migrat_file_ha_6ee811_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="migrationfieldmapping",
            unique_together={("migration_job", "column_name_in_file")},
        ),
        migrations.AlterUniqueTogether(
            name="migrationcolumnprofile",
            unique_together={("migration_job", "column_name_in_file")},
        ),
    ]
