# Generated by Django 4.2.13 on 2025-11-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("permissions", "0003_add_report_builder_permission"),
        ("hr", "0005_candidate_clearancechecklist_competency_employeeexit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hr", "HR"),
                            ("finance", "Finance"),
                            ("operations", "Operations"),
                            ("quality", "Quality"),
                            ("compliance", "Compliance"),
                            ("safety", "Safety"),
                            ("it", "IT"),
                        ],
                        default="operations",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="policies/"),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("requires_acknowledgement", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "compliance_links",
                    models.JSONField(
                        blank=True, default=list, help_text="List of {label, url} links"
                    ),
                ),
                (
                    "reading_time_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated reading time in minutes"
                    ),
                ),
                (
                    "review_cycle_months",
                    models.PositiveSmallIntegerField(
                        default=12, help_text="Recommended review cycle in months"
                    ),
                ),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audience_departments",
                    models.ManyToManyField(
                        blank=True, related_name="policy_documents", to="hr.department"
                    ),
                ),
                (
                    "audience_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="policy_documents",
                        to="permissions.role",
                    ),
                ),
                (
                    "category_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="policies.policycategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning department for this policy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="hr.department",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="policies.policydocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "change_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., created, updated, published, archived",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="policies.policydocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="policies/attachments/")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="policies.policydocument",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_acks",
                        to="companies.company",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="policies.policydocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(
                fields=["company", "code", "version"],
                name="policies_po_company_e0c289_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(
                fields=["company", "status", "category"],
                name="policies_po_company_5c6368_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policydocument",
            unique_together={("company", "code", "version")},
        ),
        migrations.AddIndex(
            model_name="policychangelog",
            index=models.Index(
                fields=["policy", "version"], name="policies_po_policy__a5e63d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyattachment",
            index=models.Index(
                fields=["policy", "uploaded_at"], name="policies_po_policy__8a3b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyacknowledgement",
            index=models.Index(
                fields=["company", "user"], name="policies_po_company_2aac63_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policyacknowledgement",
            unique_together={("policy", "user", "version")},
        ),
    ]
