# Generated by Django 4.2.7 on 2025-10-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_intercompanylink_groupaccountmap"),
        ("metadata", "0001_initial"),
        ("form_builder", "0002_dynamicentity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dynamicentity",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dynamicentity",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dynamic_entities",
                to="companies.companygroup",
            ),
        ),
        migrations.AddField(
            model_name="dynamicentity",
            name="metadata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dynamic_entities",
                to="metadata.metadatadefinition",
            ),
        ),
        migrations.AddField(
            model_name="dynamicentity",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Company"),
                    ("GROUP", "Company Group"),
                    ("GLOBAL", "Global"),
                ],
                default="COMPANY",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="form_templates",
                to="companies.companygroup",
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="layer",
            field=models.CharField(
                choices=[
                    ("CORE", "Core System"),
                    ("INDUSTRY_PACK", "Industry Pack Baseline"),
                    ("GROUP_CUSTOM", "Group Customization"),
                    ("COMPANY_OVERRIDE", "Company Override"),
                ],
                default="COMPANY_OVERRIDE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="metadata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_versions",
                to="metadata.metadatadefinition",
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Company"),
                    ("GROUP", "Company Group"),
                    ("GLOBAL", "Global"),
                ],
                default="COMPANY",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Stable identifier for the form.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="dynamicentity",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dynamic_entities",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="formtemplate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="form_templates",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="formtemplate",
            name="schema",
            field=models.JSONField(
                default=list, help_text="Ordered list of field definitions."
            ),
        ),
        migrations.AddConstraint(
            model_name="dynamicentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "COMPANY")),
                fields=("slug", "company"),
                name="uniq_dynamic_slug_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="dynamicentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GROUP")),
                fields=("slug", "company_group"),
                name="uniq_dynamic_slug_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="dynamicentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GLOBAL")),
                fields=("slug",),
                name="uniq_dynamic_slug_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="formtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "COMPANY")),
                fields=("slug", "company"),
                name="uniq_form_slug_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="formtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GROUP")),
                fields=("slug", "company_group"),
                name="uniq_form_slug_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="formtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_type", "GLOBAL")),
                fields=("slug",),
                name="uniq_form_slug_global",
            ),
        ),
    ]
