# Generated by Django 4.2.7 on 2025-10-30 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[("system", "System"), ("personal", "Personal")],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("linked_entity_type", models.CharField(blank=True, max_length=120)),
                ("linked_entity_id", models.CharField(blank=True, max_length=120)),
                (
                    "visibility_scope",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("manager_visible", "Manager Visible"),
                            ("team_visible", "Team Visible"),
                            ("exec_visible", "Executive Visible"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("calendar_event_id", models.CharField(blank=True, max_length=255)),
                ("calendar_sync_status", models.CharField(blank=True, max_length=20)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegated_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "company_group",
                    models.ForeignKey(
                        help_text="Company group this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.companygroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "due_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["company", "assigned_to", "status"],
                        name="tasks_taski_company_6ebf42_idx",
                    ),
                    models.Index(
                        fields=["company", "assigned_by"],
                        name="tasks_taski_company_02fcb5_idx",
                    ),
                    models.Index(
                        fields=["company", "due_date"],
                        name="tasks_taski_company_a731c5_idx",
                    ),
                ],
            },
        ),
    ]
