# Generated by Django 4.2.13 on 2025-11-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0009_company_currency_business_type_and_fy_cleanup"),
        ("tasks", "0005_usercalendarcredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercalendarcredential",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usercalendarcredential",
            name="company",
            field=models.ForeignKey(
                help_text="Company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="usercalendarcredential",
            name="company_group",
            field=models.ForeignKey(
                help_text="Company group this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companygroup",
            ),
        ),
    ]
