# Generated by Django 4.2.7 on 2025-10-23 06:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique company code",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z0-9]+$")
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255)),
                ("currency_code", models.CharField(default="BDT", max_length=3)),
                ("fiscal_year_start", models.DateField()),
                ("tax_id", models.CharField(max_length=50, unique=True)),
                ("registration_number", models.CharField(max_length=100)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subsidiaries",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["code"],
            },
        ),
    ]
