# Generated by Django 4.2.7 on 2025-10-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="external_db_connection",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: External database connection for this company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shared.databaseconnection",
            ),
        ),
    ]
