# Generated by Django 4.2.7 on 2025-10-27 17:48

from django.db import migrations, models
import django.db.models.deletion


def seed_default_company_group(apps, schema_editor):
    CompanyGroup = apps.get_model("companies", "CompanyGroup")
    if CompanyGroup.objects.exists():
        return
    CompanyGroup.objects.create(
        name="Default Company Group",
        db_name="cg_default",
        industry_pack_type="",
        supports_intercompany=False,
        status="active",
    )


def assign_company_group(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    CompanyGroup = apps.get_model("companies", "CompanyGroup")
    group = CompanyGroup.objects.order_by("id").first()
    if group is None:
        group = CompanyGroup.objects.create(
            name="Default Company Group",
            db_name="cg_default",
            industry_pack_type="",
            supports_intercompany=False,
            status="active",
        )
    Company.objects.filter(company_group__isnull=True).update(company_group=group)


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_external_db_connection"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "db_name",
                    models.CharField(
                        help_text="Physical Postgres database identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("industry_pack_type", models.CharField(blank=True, max_length=50)),
                ("supports_intercompany", models.BooleanField(default=False)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Company Groups",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_default_company_group, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="company",
            name="external_db_connection",
        ),
        migrations.RemoveField(
            model_name="company",
            name="parent_company",
        ),
        migrations.AddField(
            model_name="company",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="companies.companygroup",
            ),
        ),
        migrations.RunPython(assign_company_group, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="company",
            name="company_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="companies.companygroup",
            ),
        ),
    ]
