# Generated by Django 4.2.7 on 2025-10-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0003_companygroup_remove_company_external_db_connection_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InterCompanyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_entity",
                    models.CharField(
                        help_text="e.g., invoice, stock_transfer", max_length=50
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(
                        help_text="ID of the record in the initiating company",
                        max_length=100,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inter_company_links",
                        to="companies.companygroup",
                    ),
                ),
                (
                    "counterparty_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counterparty_links",
                        to="companies.company",
                    ),
                ),
                (
                    "initiating_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_links",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inter-Company Link",
                "verbose_name_plural": "Inter-Company Links",
                "unique_together": {
                    ("initiating_company", "source_entity", "source_record_id")
                },
            },
        ),
        migrations.CreateModel(
            name="GroupAccountMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_account_code",
                    models.CharField(
                        help_text="Local Chart of Account code", max_length=50
                    ),
                ),
                (
                    "consolidated_account_code",
                    models.CharField(
                        help_text="Consolidated Chart of Account code", max_length=50
                    ),
                ),
                (
                    "is_intercompany_account",
                    models.BooleanField(
                        default=False,
                        help_text="True if this account is used for inter-company transactions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_account_maps",
                        to="companies.companygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Account Map",
                "verbose_name_plural": "Group Account Maps",
                "unique_together": {("company_group", "local_account_code")},
            },
        ),
    ]
