# Generated by Django 4.2.13 on 2025-11-04 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_intercompanylink_groupaccountmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("headquarters", "Headquarters"),
                            ("factory", "Factory/Manufacturing"),
                            ("warehouse", "Warehouse"),
                            ("retail", "Retail Store"),
                            ("office", "Office"),
                            ("regional", "Regional Office"),
                            ("distribution", "Distribution Center"),
                            ("other", "Other"),
                        ],
                        default="office",
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("manager_name", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("has_warehouse", models.BooleanField(default=False)),
                (
                    "warehouse_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("operational_start_date", models.DateField(blank=True, null=True)),
                ("operational_end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Branches",
                "db_table": "branch",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "department_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("finance", "Finance"),
                            ("operations", "Operations"),
                            ("sales", "Sales"),
                            ("marketing", "Marketing"),
                            ("hr", "Human Resources"),
                            ("production", "Production"),
                            ("warehouse", "Warehouse"),
                            ("it", "IT/Systems"),
                            ("admin", "Administration"),
                            ("quality", "Quality Assurance"),
                            ("legal", "Legal"),
                            ("strategy", "Strategy"),
                            ("procurement", "Procurement"),
                            ("logistics", "Logistics"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "cost_center_code",
                    models.CharField(
                        blank=True,
                        help_text="Associated cost center if exists",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("budget_threshold_percent", models.IntegerField(default=90)),
                (
                    "requires_approval_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Transactions above this value require approval",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Departments",
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="DepartmentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("head", "Department Head"),
                            ("deputy", "Deputy Head"),
                            ("manager", "Manager"),
                            ("senior_staff", "Senior Staff"),
                            ("staff", "Staff"),
                            ("intern", "Intern"),
                        ],
                        default="staff",
                        max_length=100,
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("custom_permissions", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "department_membership",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="base_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="company",
            name="company_admin_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary admin for this company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_for_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("subsidiary", "Subsidiary"),
                    ("division", "Division"),
                    ("branch_entity", "Branch Entity"),
                    ("joint_venture", "Joint Venture"),
                    ("independent", "Independent"),
                ],
                default="independent",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="enable_inter_company_transactions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="feature_flags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="company",
            name="fiscal_year_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="fiscal_year_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="is_consolidation_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="legal_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="company",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="parent_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subsidiary_companies",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="registration_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="requires_branch_structure",
            field=models.BooleanField(
                default=False,
                help_text="If True, departments must be under branches; if False, departments attach directly",
            ),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="base_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="fiscal_year_end_month",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("holding", "Holding Company"),
                    ("consortium", "Consortium/Association"),
                    ("ngo_umbrella", "NGO Umbrella Organization"),
                    ("franchise", "Franchise Network"),
                    ("other", "Other"),
                ],
                default="holding",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="hierarchy_path",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Path for hierarchy: 1/2/3",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="is_consolidated",
            field=models.BooleanField(
                default=True, help_text="Include in group consolidation reports"
            ),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="legal_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="owner_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="owner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="owner_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_groups",
                to="companies.companygroup",
            ),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="registration_authority",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="companygroup",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.CharField(
                help_text="Unique company code",
                max_length=20,
                validators=[django.core.validators.RegexValidator("^[A-Z0-9]+$")],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_group",
            field=models.ForeignKey(
                help_text="Parent group (optional for standalone companies)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="companies.companygroup",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="fiscal_year_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="companygroup",
            name="db_name",
            field=models.CharField(
                blank=True,
                help_text="Physical Postgres database identifier (legacy)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="companygroup",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("company_group", "code")},
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["company_group", "is_active"], name="company_company_62bfd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["code"], name="company_code_2351f9_idx"),
        ),
        migrations.AddIndex(
            model_name="companygroup",
            index=models.Index(fields=["code"], name="company_gro_code_6b5d9d_idx"),
        ),
        migrations.AddIndex(
            model_name="companygroup",
            index=models.Index(
                fields=["parent_group", "is_active"],
                name="company_gro_parent__fcda3c_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="company",
            table="company",
        ),
        migrations.AlterModelTable(
            name="companygroup",
            table="company_group",
        ),
        migrations.AddField(
            model_name="departmentmembership",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.department"
            ),
        ),
        migrations.AddField(
            model_name="departmentmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Null if department is directly under company (no branch layer)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="companies.branch",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                help_text="Always scoped to a company",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_departments",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="department_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="deputy_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deputy_headed_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="departments",
                through="companies.DepartmentMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent_department",
            field=models.ForeignKey(
                blank=True,
                help_text="For hierarchical departments (e.g., Finance > Accounting > Payroll)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_departments",
                to="companies.department",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_head_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="company",
            field=models.ForeignKey(
                help_text="Parent company",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="parent_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="For hierarchical branches if needed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_branches",
                to="companies.branch",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmembership",
            index=models.Index(
                fields=["department", "is_active"],
                name="department__departm_7f60e5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmentmembership",
            unique_together={("user", "department")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["company", "branch", "is_active"],
                name="department_company_210d9f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["department_head"], name="department_departm_4c0f44_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["company", "is_active"], name="branch_company_d0bfdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["branch_type"], name="branch_branch__879f95_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together={("company", "code")},
        ),
    ]
