# Generated by Django 4.2.13 on 2025-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_branch_department_departmentmembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_data_loaded",
            field=models.BooleanField(
                default=False,
                help_text="True if industry-specific default master data has been loaded",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_data_loaded_at",
            field=models.DateTimeField(
                blank=True, help_text="When default master data was loaded", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="industry_category",
            field=models.CharField(
                choices=[
                    ("MANUFACTURING", "Manufacturing"),
                    ("TRADING", "Trading/Wholesale"),
                    ("RETAIL", "Retail"),
                    ("SERVICE", "Service Provider"),
                    ("CONSULTING", "Consulting"),
                    ("NGO", "Non-Profit/NGO"),
                    ("HEALTHCARE", "Healthcare"),
                    ("EDUCATION", "Education"),
                    ("HOSPITALITY", "Hospitality/Hotel/Restaurant"),
                    ("CONSTRUCTION", "Construction/Real Estate"),
                    ("AGRICULTURE", "Agriculture/Farming"),
                    ("TECHNOLOGY", "Technology/Software"),
                    ("TRANSPORTATION", "Transportation/Logistics"),
                    ("FINANCE", "Financial Services"),
                    ("GOVERNMENT", "Government/Public Sector"),
                ],
                default="SERVICE",
                help_text="Industry category determines default Chart of Accounts and master data",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="industry_sub_category",
            field=models.CharField(
                blank=True,
                help_text='More specific industry classification (e.g., "Textile Manufacturing")',
                max_length=100,
            ),
        ),
    ]
