# Generated by Django 4.2.13 on 2025-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_alter_company_company_group_protect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companygroup",
            name="base_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("BDT", "Bangladeshi Taka"),
                    ("INR", "Indian Rupee"),
                    ("PKR", "Pakistani Rupee"),
                    ("LKR", "Sri Lankan Rupee"),
                    ("CNY", "Chinese Yuan"),
                    ("JPY", "Japanese Yen"),
                    ("AUD", "Australian Dollar"),
                    ("CAD", "Canadian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("MYR", "Malaysian Ringgit"),
                    ("THB", "Thai Baht"),
                    ("IDR", "Indonesian Rupiah"),
                    ("PHP", "Philippine Peso"),
                    ("AED", "UAE Dirham"),
                    ("SAR", "Saudi Riyal"),
                    ("KWD", "Kuwaiti Dinar"),
                    ("OMR", "Omani Rial"),
                    ("QAR", "Qatari Riyal"),
                    ("ZAR", "South African Rand"),
                    ("NGN", "Nigerian Naira"),
                    ("GHS", "Ghanaian Cedi"),
                    ("KES", "Kenyan Shilling"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="companygroup",
            name="fiscal_year_end_month",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=12,
            ),
        ),
        migrations.AlterField(
            model_name="companygroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("holding", "Holding Company"),
                    ("consortium", "Consortium/Association"),
                    ("ngo_umbrella", "NGO Umbrella Organization"),
                    ("franchise", "Franchise Network"),
                    ("group_of_companies", "Group of Companies"),
                    ("other", "Other"),
                ],
                default="holding",
                max_length=50,
            ),
        ),
    ]
