"""
Default feature toggles to be created during initial setup.

This file defines all available features across all modules.
"""

DEFAULT_FEATURES = [
    # ========== CORE MODULES ==========

    # Dashboard Module
    {
        'module': 'dashboard',
        'key': 'module',
        'name': 'Dashboard Module',
        'description': 'Main dashboard and analytics overview',
        'icon': 'mdi-view-dashboard',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 100,
    },

    # ========== FINANCE MODULE ==========

    {
        'module': 'finance',
        'key': 'module',
        'name': 'Finance Module',
        'description': 'Complete finance and accounting module',
        'icon': 'mdi-finance',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 90,
    },
    {
        'module': 'finance',
        'key': 'chart_of_accounts',
        'name': 'Chart of Accounts',
        'description': 'Manage chart of accounts and account structure',
        'icon': 'mdi-file-tree',
        'enabled': True,
        'visible': True,
        'depends_on': ['finance.module'],
        'priority': 85,
    },
    {
        'module': 'finance',
        'key': 'journal_vouchers',
        'name': 'Journal Vouchers',
        'description': 'Create and manage journal vouchers',
        'icon': 'mdi-book-open-variant',
        'enabled': True,
        'visible': True,
        'depends_on': ['finance.module', 'finance.chart_of_accounts'],
        'priority': 84,
    },

    # ========== INVENTORY MODULE ==========

    {
        'module': 'inventory',
        'key': 'module',
        'name': 'Inventory Module',
        'description': 'Inventory and warehouse management',
        'icon': 'mdi-warehouse',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 80,
    },
    {
        'module': 'inventory',
        'key': 'products',
        'name': 'Products',
        'description': 'Product master data management',
        'icon': 'mdi-package-variant',
        'enabled': True,
        'visible': True,
        'depends_on': ['inventory.module'],
        'priority': 75,
    },
    {
        'module': 'inventory',
        'key': 'requisitions_internal',
        'name': 'Internal Requisitions',
        'description': 'Request stock from internal warehouses',
        'icon': 'mdi-file-document-edit',
        'enabled': True,
        'visible': True,
        # Allow internal requisitions even when product master is not yet configured
        'depends_on': ['inventory.module'],
        'priority': 74,
    },

    # ========== SALES MODULE ==========

    {
        'module': 'sales',
        'key': 'module',
        'name': 'Sales Module',
        'description': 'Sales and CRM functionality',
        'icon': 'mdi-cart',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 70,
        'depends_on': ['inventory.module'],
    },
    {
        'module': 'sales',
        'key': 'customers',
        'name': 'Customers',
        'description': 'Customer relationship management',
        'icon': 'mdi-account-group',
        'enabled': True,
        'visible': True,
        'depends_on': ['sales.module'],
        'priority': 65,
    },
    {
        'module': 'sales',
        'key': 'sales_orders',
        'name': 'Sales Orders',
        'description': 'Manage sales orders and quotations',
        'icon': 'mdi-file-document',
        'enabled': True,
        'visible': True,
        'depends_on': ['sales.module', 'sales.customers', 'inventory.products'],
        'priority': 64,
    },

    # ========== PROCUREMENT MODULE ==========

    {
        'module': 'procurement',
        'key': 'module',
        'name': 'Procurement Module',
        'description': 'Purchase and vendor management',
        'icon': 'mdi-shopping',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 60,
        'depends_on': ['budgeting.module', 'inventory.module', 'finance.module'],
    },
    {
        'module': 'procurement',
        'key': 'vendors',
        'name': 'Vendors',
        'description': 'Vendor master data',
        'icon': 'mdi-truck',
        'enabled': True,
        'visible': True,
        'depends_on': ['procurement.module'],
        'priority': 55,
    },
    {
        'module': 'procurement',
        'key': 'purchase_orders',
        'name': 'Purchase Orders',
        'description': 'Create and manage purchase orders',
        'icon': 'mdi-clipboard-text',
        'enabled': True,
        'visible': True,
        'depends_on': ['procurement.module', 'procurement.vendors', 'inventory.products'],
        'priority': 54,
    },
    # Inventory Purchase Requisitions (independent from Procurement module)
    {
        'module': 'inventory',
        'key': 'purchase_requisitions',
        'name': 'Purchase Requisitions',
        'description': 'Raise material requests for procurement (from Inventory)',
        'icon': 'mdi-file-document-edit-outline',
        'enabled': True,
        'visible': True,
        'depends_on': ['inventory.module'],
        'priority': 73,
    },
    # Deprecated: Procurement purchase requisitions toggle (kept for compatibility, hidden)
    {
        'module': 'procurement',
        'key': 'purchase_requisitions',
        'name': 'Purchase Requisitions (Deprecated)',
        'description': 'Deprecated: use Inventory → Purchase Requisitions',
        'icon': 'mdi-alert-decagram',
        'enabled': False,
        'visible': False,
        'status': 'deprecated',
        'depends_on': [],
        'priority': 1,
    },

    # ========== HR MODULE ==========

    {
        'module': 'hr',
        'key': 'module',
        'name': 'HR Module',
        'description': 'Human resources management',
        'icon': 'mdi-account-multiple',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 50,
        'depends_on': ['budgeting.module', 'finance.module'],
    },
    {
        'module': 'hr',
        'key': 'employees',
        'name': 'Employees',
        'description': 'Employee master data and profiles',
        'icon': 'mdi-account-tie',
        'enabled': True,
        'visible': True,
        'depends_on': ['hr.module'],
        'priority': 45,
    },
    {
        'module': 'hr',
        'key': 'payroll',
        'name': 'Payroll',
        'description': 'Payroll processing and management',
        'icon': 'mdi-currency-usd',
        'enabled': True,
        'visible': True,
        'depends_on': ['hr.module', 'hr.employees', 'finance.module'],
        'priority': 42,
    },

    # ========== PRODUCTION MODULE ==========

    {
        'module': 'production',
        'key': 'module',
        'name': 'Production Module',
        'description': 'Manufacturing and production management',
        'icon': 'mdi-factory',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 40,
        'depends_on': ['inventory.module'],
    },
    {
        'module': 'production',
        'key': 'bom',
        'name': 'Bill of Materials',
        'description': 'Define product BOMs and recipes',
        'icon': 'mdi-format-list-bulleted',
        'enabled': True,
        'visible': True,
        'depends_on': ['production.module', 'inventory.products'],
        'priority': 35,
    },
    {
        'module': 'production',
        'key': 'work_orders',
        'name': 'Work Orders',
        'description': 'Create and track work orders',
        'icon': 'mdi-clipboard-list',
        'enabled': True,
        'visible': True,
        'depends_on': ['production.module', 'production.bom'],
        'priority': 34,
    },

    # ========== OTHER MODULES ==========

    {
        'module': 'assets',
        'key': 'module',
        'name': 'Assets Module',
        'description': 'Fixed asset management',
        'icon': 'mdi-office-building',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 30,
        'depends_on': ['finance.module'],
    },

    {
        'module': 'budgeting',
        'key': 'module',
        'name': 'Budgeting Module',
        'description': 'Budget planning and control',
        'icon': 'mdi-chart-line',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 25,
        'depends_on': ['inventory.module'],
    },

    {
        'module': 'projects',
        'key': 'module',
        'name': 'Projects Module',
        'description': 'Project management and tracking',
        'icon': 'mdi-briefcase',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 20,
    },

    {
        'module': 'ai_companion',
        'key': 'module',
        'name': 'AI Assistant',
        'description': 'AI-powered assistance and automation',
        'icon': 'mdi-robot',
        'enabled': True,
        'visible': True,
        'status': 'beta',
        'priority': 15,
    },

    {
        'module': 'form_builder',
        'key': 'module',
        'name': 'Form Builder',
        'description': 'Dynamic form creation and management',
        'icon': 'mdi-form-select',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 10,
    },

    {
        'module': 'workflows',
        'key': 'module',
        'name': 'Workflows',
        'description': 'Workflow automation and approvals',
        'icon': 'mdi-chart-timeline',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 9,
    },

    {
        'module': 'report_builder',
        'key': 'module',
        'name': 'Report Builder',
        'description': 'Custom report creation',
        'icon': 'mdi-file-chart',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 8,
    },

    {
        'module': 'tasks',
        'key': 'module',
        'name': 'Tasks',
        'description': 'Task management and to-do lists',
        'icon': 'mdi-checkbox-marked',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 7,
    },

    {
        'module': 'notifications',
        'key': 'module',
        'name': 'Notifications',
        'description': 'System notifications and alerts',
        'icon': 'mdi-bell',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 6,
    },

    {
        'module': 'analytics',
        'key': 'module',
        'name': 'Analytics',
        'description': 'Business intelligence and analytics',
        'icon': 'mdi-chart-bar',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 5,
    },

    {
        'module': 'data_migration',
        'key': 'module',
        'name': 'Data Migration',
        'description': 'Data import and migration tools',
        'icon': 'mdi-database-import',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 4,
    },

    # ========== GOVERNANCE & SECTOR MODULES ==========
    {
        'module': 'policies',
        'key': 'module',
        'name': 'Policies',
        'description': 'Policies & SOPs management',
        'icon': 'mdi-shield-check',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 18,
    },
    {
        'module': 'ngo',
        'key': 'module',
        'name': 'NGO Governance',
        'description': 'NGO programs and compliance',
        'icon': 'mdi-hand-heart',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 12,
        'depends_on': ['finance.module'],
    },
    {
        'module': 'microfinance',
        'key': 'module',
        'name': 'Microfinance',
        'description': 'Loans and borrower management',
        'icon': 'mdi-bank',
        'enabled': True,
        'visible': True,
        'status': 'enabled',
        'priority': 11,
        'depends_on': ['finance.module'],
    },
    {
        'module': 'microfinance',
        'key': 'loans',
        'name': 'Loans',
        'description': 'Loan products and lending operations',
        'icon': 'mdi-cash-multiple',
        'enabled': True,
        'visible': True,
        'depends_on': ['microfinance.module', 'finance.module'],
        'priority': 10,
    },
    {
        'module': 'ngo',
        'key': 'grant_governance',
        'name': 'Grant Governance',
        'description': 'Manage grants, donors, and compliance',
        'icon': 'mdi-hand-coin',
        'enabled': True,
        'visible': True,
        'depends_on': ['ngo.module', 'finance.module'],
        'priority': 11,
    },
]
