# Generated by Django 4.2.7 on 2025-10-23 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("billing_address", models.TextField(blank=True)),
                ("shipping_address", models.TextField(blank=True)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "payment_terms",
                    models.IntegerField(default=30, help_text="Payment terms in days"),
                ),
                (
                    "customer_status",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead"),
                            ("PROSPECT", "Prospect"),
                            ("ACTIVE", "Active Customer"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="LEAD",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(max_length=50)),
                ("order_date", models.DateField()),
                ("delivery_date", models.DateField()),
                ("shipping_address", models.TextField()),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("PARTIAL", "Partially Delivered"),
                            ("DELIVERED", "Delivered"),
                            ("INVOICED", "Invoiced"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sales.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "delivered_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "line_number"],
            },
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["company", "order_date"], name="sales_sales_company_bb8f12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["company", "customer", "status"],
                name="sales_sales_company_93c0a1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesorder",
            unique_together={("company", "order_number")},
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["company", "customer_status"],
                name="sales_custo_company_2ef5da_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("company", "code")},
        ),
    ]
