# Generated by Django 4.2.7 on 2025-10-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_customer_company_group_salesorder_company_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="company_group",
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="company_group",
        ),
    ]
