# Generated by Django 4.2.13 on 2025-11-05 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "10001_item_itemcategory_alter_productcategory_options_and_more"),
        ("finance", "0010_currency_account_currency_balances_and_more"),
        ("companies", "0006_company_default_data_loaded_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0004_customer_customer_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tax configuration: {type: 'GST', cgst: 9, sgst: 9} or {type: 'VAT', rate: 15}",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tax Categories",
                "db_table": "sales_tax_category",
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "hierarchy_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Path: 1/2/3/4 for efficient hierarchy queries",
                        max_length=500,
                    ),
                ),
                ("level", models.IntegerField(default=0, editable=False)),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Sort order in listings"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured category (e-commerce)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default_template",
                    models.BooleanField(
                        default=False,
                        help_text="System default category that can be customized",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (null for root categories)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_categories",
                        to="sales.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Categories",
                "db_table": "sales_product_category",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("GOODS", "Goods"), ("SERVICE", "Service")],
                        default="GOODS",
                        help_text="Type of product",
                        max_length=20,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Standard selling price",
                        max_digits=20,
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum Retail Price",
                        max_digits=20,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Reference cost for margin calculation",
                        max_digits=20,
                    ),
                ),
                ("allow_discount", models.BooleanField(default=True)),
                (
                    "max_discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum discount percentage allowed",
                        max_digits=5,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="Harmonized System Nomenclature code for GST/VAT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Visible in customer portal/e-commerce"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Sort order in listings"),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                (
                    "legacy_product_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Link to original Product record (for migration tracking)",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Product category for classification and reporting",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.productcategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to inventory item if this product needs stock tracking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.item",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Alternative revenue account (if different from sales)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_products",
                        to="finance.account",
                    ),
                ),
                (
                    "sales_account",
                    models.ForeignKey(
                        help_text="Sales revenue account",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_products",
                        to="finance.account",
                    ),
                ),
                (
                    "tax_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tax category for automatic tax calculation",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.taxcategory",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        help_text="Unit of measure",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "sales_product",
                "ordering": ["code"],
            },
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["company", "is_active"], name="sales_produ_company_9d6b9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["company", "parent_category"],
                name="sales_produ_company_e9b8df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["hierarchy_path"], name="sales_produ_hierarc_2671a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "category"], name="sales_produ_company_22db8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "is_active"], name="sales_produ_company_bd232c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "is_published"],
                name="sales_produ_company_9d6685_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "code"], name="sales_produ_company_5846d7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("company", "code")},
        ),
    ]
